.github/workflows/ci.yml, README.md, build.sbt, core/src/main/scala/org/typelevel/otel4s/otel4s.scala, docs/index.md, java/src/main/scala/org/typelevel/otel4s/java/impl.scala, java/src/test/scala/com/example/PoC.scala
Counting this chicken before it's hatched: https://github.com/typelevel/governance/issues/43
=> Prepare for Typelevel move

project/plugins.sbt
Should help with https://github.com/typelevel/otel4s/pull/17.
=> Bump Scala.js

core/src/main/scala/org/typelevel/otel4s/otel4s.scala
The documentation is compiled from multiple sources: 
- https://opentelemetry.io/docs/reference/specification/metrics/datamodel
- Java API docs
=> Add basic documentation

java/all/src/main/scala/org/typelevel/otel4s/java/OtelJava.scala, java/metrics/src/main/scala/org/typelevel/otel4s/java/metrics/Metrics.scala, java/trace/src/main/scala/org/typelevel/otel4s/java/trace/Traces.scala
=> Move Metrics and Traces into packages

build.sbt, docs/examples/jaeger-docker.md
I've been exploring Laika's documentation recently. We can use directives to provide examples based on a choice.
=> Documentation: add choice directive (scala-cli example)

core/common/src/main/scala/org/typelevel/otel4s/Attribute.scala, core/metrics/src/test/scala/org/typelevel/otel4s/metrics/CounterSuite.scala, core/metrics/src/test/scala/org/typelevel/otel4s/metrics/HistogramSuite.scala, core/metrics/src/test/scala/org/typelevel/otel4s/metrics/UpDownCounterSuite.scala, core/trace/src/test/scala/org/typelevel/otel4s/trace/TracerSuite.scala, docs/examples/jaeger-docker.md, java/common/src/test/scala/org/typelevel/otel4s/java/ConversionsSuite.scala, java/metrics/src/test/scala/org/typelevel/otel4s/java/metrics/CounterSuite.scala, java/trace/src/test/scala/org/typelevel/otel4s/java/trace/TracerSuite.scala, testkit/metrics/jvm/src/main/scala/org/typelevel/otel4s/testkit/metrics/MetricsSdk.scala
A minor QOL improvement. 
The names are a matter of discussion.
=> Attribute - add utility `apply` method

docs/index.md
There's a lot more to expound upon than this copy of the README, but this is better than the template.
=> Refresh the index page

build.sbt
=> Release v0.1.0

java/all/src/main/scala/org/typelevel/otel4s/java/OtelJava.scala
The new release of OpenTelemetry [1.23.0](https://github.com/typelevel/otel4s/pull/131) brought a proper shutdown method.
=> Use `sdk.shutdown()` to shut all providers down

build.sbt, examples/src/main/scala/KleisliExample.scala, java/trace/src/main/scala/org/typelevel/otel4s/java/trace/Scope.scala, java/trace/src/main/scala/org/typelevel/otel4s/java/trace/SpanBuilderImpl.scala, java/trace/src/main/scala/org/typelevel/otel4s/java/trace/TraceScope.scala, java/trace/src/main/scala/org/typelevel/otel4s/java/trace/TracerImpl.scala, java/trace/src/main/scala/org/typelevel/otel4s/java/trace/TracerProviderImpl.scala, java/trace/src/main/scala/org/typelevel/otel4s/java/trace/Traces.scala, java/trace/src/main/scala/org/typelevel/otel4s/java/trace/instances.scala, java/trace/src/test/scala/org/typelevel/otel4s/java/trace/TracerSuite.scala
=> Provide cats.mtl.Local instances

build.sbt, examples/src/main/scala/TraceExample.scala
This adds an example for showing how a client, database, and trait that utilizes both of them may interact.  It tries to highlight the ways to add attributes to spans as well as different methods that can be used.
=> Add another Trace Example

build.sbt, core/common/src/main/scala/org/typelevel/otel4s/TextMapGetter.scala, core/common/src/main/scala/org/typelevel/otel4s/TextMapUpdater.scala, core/common/src/test/scala/org/typelevel/otel4s/Box.scala, core/common/src/test/scala/org/typelevel/otel4s/NotQuiteExhaustiveChecks.scala, core/common/src/test/scala/org/typelevel/otel4s/TextMapGetterSuite.scala, core/common/src/test/scala/org/typelevel/otel4s/TextMapUpdaterSuite.scala
=> Add `{Contra;In}variant` instances for `TextMap{Get;Upda}ter`

build.sbt, core/common/src/test/scala/org/typelevel/otel4s/TextMapGetterProps.scala, core/common/src/test/scala/org/typelevel/otel4s/TextMapSetterProps.scala, core/common/src/test/scala/org/typelevel/otel4s/TextMapUpdaterProps.scala
=> Add properties tests for `TextMap{Get,Set,Upda}ter`

core/metrics/src/main/scala/org/typelevel/otel4s/metrics/Meter.scala
=>  Meter summoner

java/trace/src/main/scala/org/typelevel/otel4s/java/trace/SpanBuilderImpl.scala, java/trace/src/test/scala/org/typelevel/otel4s/java/trace/TracerSuite.scala
=> [#249] Fix addAttributes not to remove previous attributes.

build.sbt, docs/examples/directory.conf, docs/examples/histogram-custom-buckets.md, examples/src/main/scala/HistogramBucketsExample.scala
I did a similar exercise at $work recently and I guess it can be helpful for everyone.
=> Provide 'Histogram custom buckets' example

docs/examples/histogram-custom-buckets.md
=> Histogram custom buckets doc: improve readability

core/common/src/main/scala/org/typelevel/otel4s/ContextPropagators.scala, core/common/src/main/scala/org/typelevel/otel4s/TextMapPropagator.scala, core/metrics/src/main/scala/org/typelevel/otel4s/metrics/Meter.scala, core/metrics/src/main/scala/org/typelevel/otel4s/metrics/MeterBuilder.scala, core/metrics/src/main/scala/org/typelevel/otel4s/metrics/MeterProvider.scala, core/trace/src/main/scala/org/typelevel/otel4s/trace/Tracer.scala, core/trace/src/main/scala/org/typelevel/otel4s/trace/TracerBuilder.scala, core/trace/src/main/scala/org/typelevel/otel4s/trace/TracerProvider.scala
Similarly to the `MeterProvider`.
=> Add `TracerProvider.noop`

core/common/src/main/scala/org/typelevel/otel4s/KindTransformer.scala, java/trace/src/test/scala/org/typelevel/otel4s/java/trace/TracerSuite.scala
Add implicit `KindTransformer` for identity (i.e.
`KindTransformer[F, F]`).
oopsie
=> Add implicit `KindTransformer` for identity

core/trace/src/main/scala/org/typelevel/otel4s/trace/TracerBuilder.scala, core/trace/src/main/scala/org/typelevel/otel4s/trace/TracerProvider.scala
I'm honestly not convinced this has sufficient value to include, but it was also super easy to implement, so I thought I'd throw it up and get others' thoughts
=> Add `Tracer{Provider,Builder}#mapK`

core/trace/src/main/scala/org/typelevel/otel4s/trace/Tracer.scala, core/trace/src/test/scala/org/typelevel/otel4s/trace/TracerSuite.scala, java/trace/src/main/scala/org/typelevel/otel4s/java/trace/SpanBackendImpl.scala, java/trace/src/main/scala/org/typelevel/otel4s/java/trace/SpanRunner.scala, java/trace/src/main/scala/org/typelevel/otel4s/java/trace/TracerImpl.scala, java/trace/src/test/scala/org/typelevel/otel4s/java/trace/TracerSuite.scala
=> Add `Tracer#currentSpanOrNoop`

docs/tracing-context-propagation.md
Closes https://github.com/typelevel/otel4s/issues/137.
=> site: add `Tracing context propagation` page

build.sbt, java/all/src/main/scala/org/typelevel/otel4s/java/OtelJava.scala, java/common/src/main/scala/org/typelevel/otel4s/java/Conversions.scala
Relates to https://github.com/typelevel/otel4s/issues/396#issuecomment-1847649029.
=> Remove SDK dependency from `otel4s-java-common`

build.sbt, core/common/src/main/scala/org/typelevel/otel4s/instances/AllInstances.scala, core/common/src/main/scala/org/typelevel/otel4s/instances/LocalInstances.scala, core/common/src/main/scala/org/typelevel/otel4s/instances/package.scala, core/common/src/test/scala/org/typelevel/otel4s/instances/LocalInstancesSuite.scala, docs/instrumentation/tracing-java-interop.md, docs/tracing-context-propagation.md, examples/src/main/scala/PekkoHttpExample.scala, oteljava/all/src/main/scala/org/typelevel/otel4s/oteljava/OtelJava.scala, oteljava/trace/src/main/scala/org/typelevel/otel4s/oteljava/trace/Traces.scala, oteljava/trace/src/test/scala/org/typelevel/otel4s/oteljava/trace/TracerSuite.scala, sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/SdkTraceScopeSuite.scala
Follow up to https://github.com/typelevel/otel4s/pull/400#discussion_r1432878104.
=> Move `instances` to the `core-common` package

core/trace/src/main/scala/org/typelevel/otel4s/trace/Span.scala, sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/SdkSpanBuilder.scala, sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/TracerSharedState.scala, sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/samplers/ParentBasedSampler.scala, sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/samplers/Sampler.scala, sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/samplers/TraceIdRatioBasedSampler.scala, sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/SdkSpanBuilderSuite.scala, sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/samplers/ShouldSampleInput.scala
|-|-|
| Java implementation | [SdkSpanBuilder.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkSpanBuilder.java) |
=> sdk-trace: add `SdkSpanBuilder`

core/common/src/main/scala/org/typelevel/otel4s/Attributes.scala, core/common/src/test/scala/org/typelevel/otel4s/AttributesProps.scala
Add `Attributes#updated` as well as `Attributes#+` alias for it.
Add `Attributes#concat` invariant overload as well as `Attributes#++` alias for it.
=> Add `Attributes#{updated,concat}`

core/trace/src/main/scala/org/typelevel/otel4s/trace/TraceState.scala
I was wrong, sorry 😕 see https://github.com/lampepfl/dotty/issues/19348#issuecomment-1881464246.
=> Remove `@threadUnsafe` annotation

sdk/common/src/main/scala/org/typelevel/otel4s/sdk/TelemetryResource.scala, sdk/common/src/test/scala/org/typelevel/otel4s/sdk/TelemetryResourceLawTests.scala, sdk/common/src/test/scala/org/typelevel/otel4s/sdk/TelemetryResourceProps.scala, sdk/common/src/test/scala/org/typelevel/otel4s/sdk/TelemetryResourceSuite.scala, sdk/common/src/test/scala/org/typelevel/otel4s/sdk/scalacheck/Arbitraries.scala, sdk/common/src/test/scala/org/typelevel/otel4s/sdk/scalacheck/Cogens.scala, sdk/common/src/test/scala/org/typelevel/otel4s/sdk/scalacheck/Gens.scala, sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/SdkSpanBackend.scala, sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/TracerSharedState.scala, sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/data/SpanData.scala, sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/SdkSpanBackendSuite.scala, sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/SdkSpanBuilderSuite.scala, sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/scalacheck/Cogens.scala, sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/scalacheck/Gens.scala
=> Rename `Resource` -> `TelemetryResource`

core/metrics/src/main/scala/org/typelevel/otel4s/metrics/MeasurementValue.scala, core/metrics/src/main/scala/org/typelevel/otel4s/metrics/Meter.scala, core/metrics/src/main/scala/org/typelevel/otel4s/metrics/ObservableGauge.scala, oteljava/metrics/src/main/scala/org/typelevel/otel4s/oteljava/metrics/MeterImpl.scala, oteljava/metrics/src/main/scala/org/typelevel/otel4s/oteljava/metrics/ObservableGaugeBuilderImpl.scala, oteljava/metrics/src/test/scala/org/typelevel/otel4s/oteljava/metrics/ObservableSuite.scala
=> metrics: make `Meter[F].observableGauge` generic

core/metrics/src/main/scala/org/typelevel/otel4s/metrics/MeasurementValue.scala, core/metrics/src/main/scala/org/typelevel/otel4s/metrics/Meter.scala, core/metrics/src/main/scala/org/typelevel/otel4s/metrics/ObservableCounter.scala, examples/src/main/scala/ObservableExample.scala, oteljava/metrics/src/main/scala/org/typelevel/otel4s/oteljava/metrics/MeterImpl.scala, oteljava/metrics/src/main/scala/org/typelevel/otel4s/oteljava/metrics/ObservableCounterBuilderImpl.scala, oteljava/metrics/src/test/scala/org/typelevel/otel4s/oteljava/metrics/ObservableSuite.scala
Follow up to https://github.com/typelevel/otel4s/issues/432.
=> metrics: make `Meter[F].observableCounter` generic

core/metrics/src/main/scala/org/typelevel/otel4s/metrics/MeasurementValue.scala, core/metrics/src/main/scala/org/typelevel/otel4s/metrics/Meter.scala, core/metrics/src/main/scala/org/typelevel/otel4s/metrics/ObservableUpDownCounter.scala, oteljava/metrics/src/main/scala/org/typelevel/otel4s/oteljava/metrics/MeterImpl.scala, oteljava/metrics/src/main/scala/org/typelevel/otel4s/oteljava/metrics/ObservableUpDownCounterBuilderImpl.scala, oteljava/metrics/src/test/scala/org/typelevel/otel4s/oteljava/metrics/ObservableSuite.scala
Follow up to https://github.com/typelevel/otel4s/issues/432.
=> metrics: make `Meter[F].observableUpDownCounter` generic

core/common/src/main/scala/org/typelevel/otel4s/baggage/Baggage.scala, core/common/src/test/scala/org/typelevel/otel4s/baggage/BaggageSuite.scala, sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/SdkContextKeys.scala
|-|-|
| Spec | https://opentelemetry.io/docs/specs/otel/baggage/api/ |
| Java implementation | [Baggage.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/api/all/src/main/java/io/opentelemetry/api/baggage/Baggage.java) |
=> sdk-common: add `Baggage`

sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/context/propagation/B3Propagator.scala, sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/context/propagation/B3PropagatorSuite.scala
|-|-|
| Spec | https://opentelemetry.io/docs/specs/otel/context/api-propagators/#b3-requirements <br> https://github.com/openzipkin/b3-propagation |
| Java implementation | [B3Propagator.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/B3Propagator.java)|
=> sdk-trace: add `B3Propagator`

core/trace/src/main/scala/org/typelevel/otel4s/trace/SpanContext.scala, core/trace/src/test/scala/org/typelevel/otel4s/trace/scalacheck/Gens.scala, sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/propagation/W3CTraceContextPropagator.scala, sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/propagation/W3CTraceContextPropagatorSuite.scala
|-|-|
| Spec | https://www.w3.org/TR/trace-context/ |
| Java implementation | [W3CTraceContextPropagator.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/api/all/src/main/java/io/opentelemetry/api/trace/propagation/W3CTraceContextPropagator.java) |
=> sdk-trace: add `W3CTraceContextPropagator`

sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/context/propagation/W3CBaggagePropagator.scala, sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/context/propagation/W3CBaggagePropagatorSuite.scala, sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/context/propagation/W3CTraceContextPropagatorSuite.scala
|-|-|
| Spec | https://www.w3.org/TR/baggage/ |
| Java implementation | [W3CBaggagePropagator.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/api/all/src/main/java/io/opentelemetry/api/baggage/propagation/W3CBaggagePropagator.java) |
=> sdk-trace: add `W3CBaggagePropagator`

sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/autoconfigure/SamplerAutoConfigure.scala, sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/autoconfigure/SamplerAutoConfigureSuite.scala
Users may configure third-party samplers.
=> sdk-trace: make `SamplerAutoConfigure` extendable

core/trace/src/main/scala-2/org/typelevel/otel4s/trace/SpanMacro.scala, core/trace/src/main/scala-3/org/typelevel/otel4s/trace/SpanMacro.scala, core/trace/src/main/scala/org/typelevel/otel4s/trace/Span.scala, core/trace/src/main/scala/org/typelevel/otel4s/trace/SpanFinalizer.scala, core/trace/src/main/scala/org/typelevel/otel4s/trace/StatusCode.scala, core/trace/src/test/scala/org/typelevel/otel4s/trace/StatusCodeSuite.scala, core/trace/src/test/scala/org/typelevel/otel4s/trace/TracerSuite.scala, core/trace/src/test/scala/org/typelevel/otel4s/trace/scalacheck/Arbitraries.scala, core/trace/src/test/scala/org/typelevel/otel4s/trace/scalacheck/Cogens.scala, core/trace/src/test/scala/org/typelevel/otel4s/trace/scalacheck/Gens.scala, oteljava/trace/src/main/scala/org/typelevel/otel4s/oteljava/trace/SpanBackendImpl.scala, scalafix/input/src/main/scala/example/V0_5_0Rewrites.scala, scalafix/output/src/main/scala/example/V0_5_0Rewrites.scala, scalafix/rules/src/main/scala/org/typelevel/otel4s/scalafix/V0_5_0Rewrites.scala, sdk-exporter/trace/src/main/scala/org/typelevel/otel4s/sdk/exporter/otlp/trace/SpansProtoEncoder.scala, sdk-exporter/trace/src/test/scala/org/typelevel/otel4s/sdk/exporter/otlp/trace/OtlpHttpSpanExporterSuite.scala, sdk-exporter/trace/src/test/scala/org/typelevel/otel4s/sdk/exporter/otlp/trace/SpansJsonCodecs.scala, sdk-exporter/trace/src/test/scala/org/typelevel/otel4s/sdk/exporter/otlp/trace/SpansProtoEncoderSuite.scala, sdk/all/src/test/scala/org/typelevel/otel4s/sdk/trace/SdkTracerSuite.scala, sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/SdkSpanBackend.scala, sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/data/StatusData.scala, sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/SdkSpanBackendSuite.scala, sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/data/StatusDataSuite.scala, sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/processor/SimpleSpanProcessorSuite.scala, sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/scalacheck/Cogens.scala
=> trace: rename `Status` to `StatusCode`

.scala-steward.conf
=> SemanticConventionsGenerator hook: generate headers

sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/view/RegisteredView.scala, sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/view/ViewRegistry.scala, sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/view/ViewRegistrySuite.scala
|-|-|
| Java implementation | [ViewRegistry.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/view/ViewRegistry.java)  |
=> sdk-metrics: add `ViewRegistry`

sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/internal/storage/MetricStorage.scala
|-|-|
| Spec | https://opentelemetry.io/docs/specs/otel/metrics/sdk/#last-value-aggregation |
| Java implementation | [MetricStorage.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/MetricStorage.java)  |
=> sdk-metrics: add `MetricStorage`

.github/workflows/ci.yml, build.sbt, sdk-exporter/metrics/src/main/scala/org/typelevel/otel4s/sdk/exporter/otlp/metrics/MetricsProtoEncoder.scala, sdk-exporter/metrics/src/test/scala/org/typelevel/otel4s/sdk/exporter/otlp/metrics/MetricsJsonCodecs.scala, sdk-exporter/metrics/src/test/scala/org/typelevel/otel4s/sdk/exporter/otlp/metrics/MetricsProtoEncoderSuite.scala, sdk/common/src/test/scala/org/typelevel/otel4s/sdk/scalacheck/Gens.scala, sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/aggregation/ExplicitBucketHistogramAggregatorSuite.scala, sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/aggregation/SumAggregatorSuite.scala, sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/scalacheck/Gens.scala, sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/scalacheck/Gens.scala
|-|-|
| Spec | https://github.com/open-telemetry/opentelemetry-proto/blob/v1.2.0/opentelemetry/proto/metrics/v1/metrics.proto |
=> sdk-metrics-exporter: add `MetricsProtoEncoder`

core/common/src/test/scala/org/typelevel/otel4s/scalacheck/Gens.scala, core/trace/src/test/scala/org/typelevel/otel4s/trace/scalacheck/Gens.scala, oteljava/trace/src/test/scala/org/typelevel/otel4s/oteljava/trace/SpanContextSuite.scala, sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/scalacheck/Gens.scala, sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/samplers/TraceIdRatioBasedSamplerSuite.scala
A few minor improvements to generate realistic and valid data
=> sdk tests: generate more realistic data, omit `suchThat`

sdk/all/src/test/scala/org/typelevel/otel4s/sdk/OpenTelemetrySdkSuite.scala, sdk/common/src/test/scala/org/typelevel/otel4s/sdk/test/NoopConsole.scala, sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/internal/exporter/RegisteredReader.scala, sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/internal/storage/MetricStorage.scala, sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/internal/storage/SynchronousStorage.scala, sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/internal/storage/SynchronousStorageSuite.scala, sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/SdkSpanBackendSuite.scala, sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/SdkTracesSuite.scala, sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/autoconfigure/SpanExportersAutoConfigureSuite.scala, sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/processor/BatchSpanProcessorSuite.scala, sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/processor/SimpleSpanProcessorSuite.scala
|-|-|
| Java implementation | [DefaultSynchronousMetricStorage.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/DefaultSynchronousMetricStorage.java)  |  |
=> sdk-metrics: add `SynchronousStorage`

sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/internal/storage/AsynchronousStorage.scala, sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/internal/storage/MetricStorage.scala, sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/internal/storage/AsynchronousStorageSuite.scala
|-|-|
| Java implementation | [AsynchronousMetricStorage.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/AsynchronousMetricStorage.java)  |  |
=> sdk-metrics: add `AsynchronousStorage`

sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/internal/SdkObservableMeasurement.scala, sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/exporter/InMemoryMetricReader.scala, sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/internal/SdkObservableMeasurementSuite.scala, sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/internal/storage/AsynchronousStorageSuite.scala, sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/internal/storage/SynchronousStorageSuite.scala
|-|-|
| Java implementation | [SdkObservableMeasurement.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/SdkObservableMeasurement.java)  |  |
=> sdk-metrics: add `SdkObservableMeasurement`

sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/aggregation/ExplicitBucketHistogramAggregator.scala, sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/aggregation/LastValueAggregator.scala, sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/aggregation/SumAggregator.scala, sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/internal/MetricDescriptor.scala, sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/internal/MetricStorageRegistry.scala, sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/internal/MetricStorageRegistrySuite.scala
|-|-|
| Java implementation | [MetricStorageRegistry.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/MetricStorageRegistry.java)  |  |
=> sdk-metrics: add `MetricStorageRegistry`

sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/aggregation/ExplicitBucketHistogramAggregator.scala, sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/exporter/AggregationSelector.scala, sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/internal/CallbackRegistration.scala, sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/internal/MeterSharedState.scala, sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/internal/MeterSharedStateSuite.scala, sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/internal/SdkObservableMeasurementSuite.scala, sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/internal/storage/AsynchronousStorageSuite.scala, sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/internal/storage/SynchronousStorageSuite.scala, sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/test/PointDataUtils.scala
|-|-|
| Java implementation | [MeterSharedState.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/MeterSharedState.java)  |  |
=> sdk-metrics: add `MeterSharedState`

sdk/common/src/main/scala/org/typelevel/otel4s/sdk/autoconfigure/Config.scala, sdk/common/src/test/scala/org/typelevel/otel4s/sdk/autoconfigure/ConfigSuite.scala
=> sdk-common: config Duration decoder - decode number as milliseconds

sdk-exporter/common/src/main/scala/org/typelevel/otel4s/sdk/exporter/otlp/OtlpHttpClient.scala, sdk-exporter/common/src/main/scala/org/typelevel/otel4s/sdk/exporter/otlp/autoconfigure/OtlpHttpClientAutoConfigure.scala, sdk-exporter/metrics/src/test/scala/org/typelevel/otel4s/sdk/exporter/otlp/metrics/autoconfigure/OtlpMetricExporterAutoConfigureSuite.scala, sdk-exporter/trace/src/test/scala/org/typelevel/otel4s/sdk/exporter/otlp/trace/autoconfigure/OtlpSpanExporterAutoConfigureSuite.scala
=> sdk-exporter: properly construct endpoint URI

core/metrics/src/main/scala/org/typelevel/otel4s/metrics/BucketBoundaries.scala, core/metrics/src/test/scala/org/typelevel/otel4s/metrics/BaseMeterSuite.scala, core/metrics/src/test/scala/org/typelevel/otel4s/metrics/BucketBoundariesSuite.scala, sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/Aggregation.scala, sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/exemplar/ExemplarReservoirSuite.scala
A quality of life improvement.
=> core-metrics: add varargs apply to the BucketBoundaries

docs/examples/grafana/README.md
Based on the https://github.com/keuhdall/otel4s-grafana-example/pull/33.
=> docs: update Grafana example

docs/sdk/aws-xray-propagator.md, sdk-contrib/aws/xray-propagator/src/main/scala/org/typelevel/otel4s/sdk/contrib/aws/context/propagation/AWSXRayLambdaPropagator.scala, sdk-contrib/aws/xray-propagator/src/main/scala/org/typelevel/otel4s/sdk/contrib/aws/context/propagation/AWSXRayPropagator.scala, sdk-contrib/aws/xray-propagator/src/test/scala/org/typelevel/otel4s/sdk/contrib/aws/context/propagation/AWSXRayLambdaPropagatorSuite.scala
A special case for AWS Lambda.
=> sdk-contrib: add `AWSXRayLambdaPropagator` module

README.md, docs/index.md
=> docs: improve overview, describe features

docs/examples/grafana/README.md, docs/examples/grafana/dashboards/metrics-dashboard.json, docs/examples/grafana/dashboards/traces-dashboard.json
Switches from Jaeger to Tempo but I thought it would also benefit from not showing Jaeger twice.
=> docs: simplified docker setup with otel-lgtm image

core/common/src/main/scala/org/typelevel/otel4s/Attribute.scala, core/common/src/test/scala/org/typelevel/otel4s/AttributeSuite.scala
Add implicit `Attribute.From` instances for integer primitives to be used in `Attribute[Long]`s and for `Seq`s of integer primitives to be used in `Attribute[Seq[Long]]`s.
Add implicit derivation of `Attribute.From[Seq[V], Seq[K]]` given an implicit `Attribute.From[V, K]`.
Make input type of `Attribute.From` contravariant.
=> Add implicit `Attribute.From` instances

core/common/src/main/scala/org/typelevel/otel4s/KindTransformer.scala, core/trace/src/test/scala/org/typelevel/otel4s/trace/BaseTracerSuite.scala
Remove unsound `KindTransformer` instance for `StateT`.
Add `KindTransformer` instance for `WriterT`.
Lighten context bound on `KindTransformer` instance for `Resource`
from `MonadCancelThrow` to `MonadCancel`.
=> Fix `KindTransformer` instances

core/metrics/src/main/scala/org/typelevel/otel4s/metrics/ObservableCounter.scala, core/metrics/src/main/scala/org/typelevel/otel4s/metrics/ObservableUpDownCounter.scala, sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/NoopInstrumentBuilder.scala
=> Allocate noop meter instruments only once

core/common/src/main/scala/org/typelevel/otel4s/Attributes.scala, core/common/src/test/scala/org/typelevel/otel4s/AttributeSuite.scala
=> core-common: add `Attributes.Make`
