typelevel/otel4s

- build.sbt
This should fix the header issue that started breaking in 2023.
> Set startYear

- core/trace/src/main/scala/org/typelevel/otel4s/trace/Tracer.scala
Adding the `Tracer` summoner to the companion object.
See #87
> Add Tracer summoner

- .github/workflows/ci.yml
- build.sbt
- examples/src/main/scala/TracingExample.scala
- java/all/src/main/scala/org/typelevel/otel4s/java/OtelJava.scala
- java/auto/src/main/scala/org/typelevel/otel4s/java/auto/OtelJavaAuto.scala
- java/common/src/main/scala/org/typelevel/otel4s/java/Conversions.scala
Proposes a new module based on the sdk-autoconfiguration.  This makes it much easier to get started and shuts everything down properly using Cats Effect.  This is an evolution of #90.
> Add java-auto module and tracing example

- build.sbt
- java/common/src/main/scala/org/typelevel/otel4s/java/Conversions.scala
- java/common/src/test/scala/org/typelevel/otel4s/java/ConversionsSuite.scala
- java/trace/src/main/scala/org/typelevel/otel4s/java/trace/SpanBuilderImpl.scala
- java/trace/src/test/scala/org/typelevel/otel4s/java/trace/TracerSuite.scala
An anonymous class has different hashing logic. Therefore, identical attribute keys were not equal.
> Conversions: use builder methods rather than creating an anonymous class

- java/trace/src/main/scala/org/typelevel/otel4s/java/trace/TraceScope.scala
It's a private API, so it really doesn't matter much.  And most things (all things?) with `LiftIO` are going to have a `Sync` instance anyway.  But it's good hygiene.
> Remove sync from TraceScope.fromIOLocal

- build.sbt
- core/trace/src/main/scala/org/typelevel/otel4s/trace/Span.scala
- core/trace/src/main/scala/org/typelevel/otel4s/trace/SpanBuilder.scala
- core/trace/src/main/scala/org/typelevel/otel4s/trace/SpanOps.scala
- java/trace/src/main/scala/org/typelevel/otel4s/java/trace/SpanBackendImpl.scala
- java/trace/src/main/scala/org/typelevel/otel4s/java/trace/SpanBuilderImpl.scala
- java/trace/src/main/scala/org/typelevel/otel4s/java/trace/SpanRunner.scala
- java/trace/src/main/scala/org/typelevel/otel4s/java/trace/TracerImpl.scala
- java/trace/src/test/scala/org/typelevel/otel4s/java/trace/TracerSuite.scala
While cleaning up the internal implementation, I spotted a few inconsistencies regarding start/end time selections.
Before (main branch):
|                                          | start_timestamp     | end_timestamp       |
|------------------------------------------|---------------------|---------------------|
| `ops.use`. builder has start time            | builder_start       | `Clock[F].realTime` |
| `ops.use`                                    | `Clock[F].realTime` | `Clock[F].realTime` |
| `ops.startUnmanaged`. builder has start time | builder_start       | **j_span.end**          |
| `ops.startUnmanaged`                         | **j_span.start**        | **j_span.end**          |
After (this branch):
|                                          | start_timestamp     | …
> Move `SpanRunner` outside  `SpanBuilderImpl`

- java/trace/src/main/scala/org/typelevel/otel4s/java/trace/SpanBuilderImpl.scala
- java/trace/src/test/scala/org/typelevel/otel4s/java/trace/TracerSuite.scala
Makes `resourceSpan.surround` and `resourceSpan.use_` consistent with `resourceSpan.use`.
Fixes #126.
> Fix resourceSpan surround

- build.sbt
- examples/src/main/scala/KleisliExample.scala
- java/all/src/main/scala/org/typelevel/otel4s/java/OtelJava.scala
- java/common/src/main/scala/org/typelevel/otel4s/java/instances.scala
- java/trace/src/main/scala/org/typelevel/otel4s/java/trace/Scope.scala
- java/trace/src/main/scala/org/typelevel/otel4s/java/trace/SpanBuilderImpl.scala
- java/trace/src/main/scala/org/typelevel/otel4s/java/trace/TraceScope.scala
- java/trace/src/main/scala/org/typelevel/otel4s/java/trace/TracerImpl.scala
- java/trace/src/main/scala/org/typelevel/otel4s/java/trace/TracerProviderImpl.scala
- java/trace/src/main/scala/org/typelevel/otel4s/java/trace/Traces.scala
- java/trace/src/main/scala/org/typelevel/otel4s/java/trace/instances.scala
- java/trace/src/test/scala/org/typelevel/otel4s/java/trace/TracerSuite.scala
Extends #119, but is more experimental.
Instead of exposing `Scope`, this pivots back toward the Otel spec of having a well-known "context" object.  We choose Typelevel Vault.  The operation names aren't quite right (`lookup` vs. `get`, `insert` vs. `set`), but it has the correct properties:
* immutable
* typed, unique keys
As alluded to on other PRs, the Vault gets messy if we ever need a key with a type parameter, but maybe we can avoid that!
> Make Vault the top-level context

- benchmarks/src/main/scala/org/typelevel/otel4s/benchmarks/TraceBenchmark.scala
- core/metrics/src/main/scala/org/typelevel/otel4s/metrics/Meter.scala
- core/metrics/src/main/scala/org/typelevel/otel4s/metrics/ObservableCounter.scala
- core/metrics/src/main/scala/org/typelevel/otel4s/metrics/ObservableGauge.scala
- core/metrics/src/main/scala/org/typelevel/otel4s/metrics/ObservableInstrumentBuilder.scala
- core/metrics/src/main/scala/org/typelevel/otel4s/metrics/ObservableMeasurement.scala
- core/metrics/src/main/scala/org/typelevel/otel4s/metrics/ObservableUpDownCounter.scala
- core/metrics/src/test/scala/org/typelevel/otel4s/metrics/ObservableSuite.scala
- docs/examples/honeycomb.md
- docs/examples/jaeger-docker.md
- examples/src/main/scala/KleisliExample.scala
- examples/src/main/scala/ObservableExample.scala
- examples/src/main/scala/TraceExample.scala
- examples/src/main/scala/TracingExample.scala
- java/all/src/main/scala/org/typelevel/otel4s/java/OtelJava.scala
- java/metrics/src/main/scala/org/typelevel/otel4s/java/metrics/MeterBuilderImpl.scala
- java/metrics/src/main/scala/org/typelevel/otel4s/java/metrics/MeterImpl.scala
- java/metrics/src/main/scala/org/typelevel/otel4s/java/metrics/MeterProviderImpl.scala
- java/metrics/src/main/scala/org/typelevel/otel4s/java/metrics/ObservableCounterBuilderImpl.scala
- java/metrics/src/main/scala/org/typelevel/otel4s/java/metrics/ObservableDoubleImpl.scala
- java/metrics/src/main/scala/org/typelevel/otel4s/java/metrics/ObservableGaugeBuilderImpl.scala
- java/metrics/src/main/scala/org/typelevel/otel4s/java/metrics/ObservableLongImpl.scala
- java/metrics/src/main/scala/org/typelevel/otel4s/java/metrics/ObservableUpDownCounterBuilderImpl.scala
- java/metrics/src/test/scala/org/typelevel/otel4s/java/metrics/CounterSuite.scala
- java/metrics/src/test/scala/org/typelevel/otel4s/java/metrics/ObservableSuite.scala
Fixes #158
Fixes #159
@iRevive Before I work more on this, how do you think the API looks?
> Observable instruments

- core/metrics/src/main/scala/org/typelevel/otel4s/metrics/Measurement.scala
- core/metrics/src/main/scala/org/typelevel/otel4s/metrics/Meter.scala
- core/metrics/src/main/scala/org/typelevel/otel4s/metrics/ObservableInstrumentBuilder.scala
- core/metrics/src/test/scala/org/typelevel/otel4s/metrics/ObservableSuite.scala
- java/metrics/src/main/scala/org/typelevel/otel4s/java/metrics/ObservableCounterBuilderImpl.scala
- java/metrics/src/main/scala/org/typelevel/otel4s/java/metrics/ObservableGaugeBuilderImpl.scala
- java/metrics/src/main/scala/org/typelevel/otel4s/java/metrics/ObservableUpDownCounterBuilderImpl.scala
- java/metrics/src/test/scala/org/typelevel/otel4s/java/metrics/ObservableSuite.scala
I think this would be a good addition even though the approaches seem equivalent.
From the [docs](https://opentelemetry.io/docs/reference/specification/metrics/api/#asynchronous-instrument-api)
> 
> [OpenTelemetry API](https://opentelemetry.io/docs/reference/specification/overview/#api) authors MAY decide what is the idiomatic approach for capturing measurements from callback functions. Here are some examples:
> - Return a list (or tuple, generator, enumerator, etc.) of individual Measurement values.
> - Pass an Observable Result as a formal parameter of the callback, where result.Observe() captures individual Measurement values.
The only thing I am not sure of is the naming, and whether to include the default implementation.
> Add alternative way of constructing observable instruments

- java/all/src/main/scala/org/typelevel/otel4s/java/OtelJava.scala
Just a local variable name.  Nothing exciting.
> Typo: s/contentPropagators/contextPropagators/

- build.sbt
- core/all/src/main/scala/org/typelevel/otel4s/Otel4s.scala
- java/all/src/main/scala/org/typelevel/otel4s/java/OtelJava.scala
- java/all/src/test/scala/org/typelevel/otel4s/java/OtelJavaSuite.scala
This is super not ready, just opening an early draft for visibility. Meant for #188. 
I think I realized after this first commit that since Otel4s is a trait, the implementation of `toString` shouldn't lie here (instead, it should just specify that a String is returned) -- is this correct? (And we leave the implementation to all the things with type `Otel4s[F[_]]` / all the things that extend `Otel4s[F[_]]`?)
> Basic reporting through toString 

- core/trace/src/main/scala/org/typelevel/otel4s/trace/Tracer.scala
Simplify `Tracer.Meta#noopResSpan` by making it a `final def` that always calls `#noopSpanBuilder.wrapResource`, so that implementations of `Tracer.Meta` do not need to implement `#noopResSpan`.
> Simplify `Tracer.Meta#noopResSpan`

- build.sbt
- java/common/src/main/scala/org/typelevel/otel4s/java/instances.scala
- java/common/src/test/scala/org/typelevel/otel4s/java/InstancesSuite.scala
Closes #195
This PR makes the Local instance for IO (backed by a IOLocal) public so users don't have to reimplement it themselves. Hopefully it will be added to Cats Effect but until then users can use this.
> Make Local instance for IOLocal public and add law tests

- core/trace/src/main/scala/org/typelevel/otel4s/trace/Tracer.scala
- java/trace/src/main/scala/org/typelevel/otel4s/java/trace/TracerBuilderImpl.scala
- java/trace/src/main/scala/org/typelevel/otel4s/java/trace/TracerImpl.scala
- java/trace/src/main/scala/org/typelevel/otel4s/java/trace/TracerProviderImpl.scala
- java/trace/src/test/scala/org/typelevel/otel4s/java/trace/TracerSuite.scala
Add `Tracer#propagate` for propagating to an arbitrary carrier without having to carry around the context `Vault` yourself.
Addresses request in #89
> Add `Tracer#propagate`

- java/trace/src/main/scala/org/typelevel/otel4s/java/ContextConversions.scala
- java/trace/src/main/scala/org/typelevel/otel4s/java/trace/TracerBuilderImpl.scala
- java/trace/src/main/scala/org/typelevel/otel4s/java/trace/TracerImpl.scala
- java/trace/src/main/scala/org/typelevel/otel4s/java/trace/TracerProviderImpl.scala
- java/trace/src/test/scala/org/typelevel/otel4s/java/trace/TracerSuite.scala
Closes #277.
While reviewing the #291, I spotted the reason behind #277.
> `Tracer#joinOrRoot` - propagate extracted headers downstream

- core/common/src/main/scala/org/typelevel/otel4s/KindTransformer.scala
- core/common/src/main/scala/org/typelevel/otel4s/meta/InstrumentMeta.scala
- core/trace/src/main/scala/org/typelevel/otel4s/trace/Span.scala
- core/trace/src/main/scala/org/typelevel/otel4s/trace/SpanBuilder.scala
- core/trace/src/main/scala/org/typelevel/otel4s/trace/SpanOps.scala
- core/trace/src/main/scala/org/typelevel/otel4s/trace/Tracer.scala
- java/trace/src/test/scala/org/typelevel/otel4s/java/trace/TracerSuite.scala
Add `mapK` to `Tracer`, `Tracer.Meta`, `SpanBuilder`, `SpanOps`, `Span`, `Span.Backend`, and `InstrumentMeta`.
Add `KindTransformer` type used by `mapK` implementation, allowing for a single `mapK` implementation that supports many transformation target types (`OptionT`, `EitherT`, `IorT`, `StateT`, `Kliesli`, `Resource`) with very little work needed to add additional or custom ones.
see #261 for previous work, and #264 for a less complex but less powerful alternative
> Add `mapK` to `Tracer`, `SpanBuilder`, etc.

- benchmarks/src/main/scala/org/typelevel/otel4s/benchmarks/TraceStateBenchmark.scala
- core/trace/src/main/scala/org/typelevel/otel4s/trace/SpanContext.scala
- core/trace/src/main/scala/org/typelevel/otel4s/trace/TraceState.scala
- core/trace/src/test/scala/org/typelevel/otel4s/trace/TraceStateSuite.scala
- java/trace/src/main/scala/org/typelevel/otel4s/java/trace/WrappedSpanContext.scala
|-|-|
| Spec | https://opentelemetry.io/docs/specs/otel/trace/api/#tracestate </br> https://www.w3.org/TR/trace-context/#tracestate-header-field-values |
| Java implementation | [TraceState.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/api/all/src/main/java/io/opentelemetry/api/trace/TraceState.java) </br> [ArrayBasedTraceStateBuilder.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/api/all/src/main/java/io/opentelemetry/api/trace/ArrayBasedTraceStateBuilder.java) |
____
Our implementation is ~30-40% slower than Java.   
Also, for whatever reason, `otel4s_oneItem` is 10 times faster ¯\_(ツ)_/¯.
I would say the current performance is acceptable. And we can always rewrite it using an array under the hood if we want. 
```
[info] …
```
> trace core: add `TraceState`

- build.sbt
- sdk/common/src/main/scala/org/typelevel/otel4s/sdk/common/InstrumentationScope.scala
- sdk/common/src/test/scala/org/typelevel/otel4s/sdk/common/InstrumentationScopeSuite.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/samplers/SamplingDecision.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/samplers/SamplingDecisionSuite.scala
|-|-|
| Spec | https://opentelemetry.io/docs/specs/otel/glossary/#instrumentation-scope </br> https://opentelemetry.io/docs/specs/otel/trace/api/#get-a-tracer|
| Java implementation | [InstrumentationScopeInfo.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/common/src/main/java/io/opentelemetry/sdk/common/InstrumentationScopeInfo.java) |
____
I started decoupling #325 into smaller changes to simplify the review process.
> sdk-common: add `InstrumentationScope`

- core/trace/src/main/scala/org/typelevel/otel4s/trace/TraceState.scala
- java/common/src/main/scala/org/typelevel/otel4s/java/TextMapPropagatorImpl.scala
- java/trace/src/main/scala/org/typelevel/otel4s/java/trace/WrappedSpanContext.scala
To avoid unnecessary synchronization for lazily initializing pure values.
https://scala-lang.org/api/3.x/scala/annotation/threadUnsafe.html#
> Apply `@threadUnsafe3` annotation to `lazy val`s

- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/data/LinkData.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/Arbitraries.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/Cogens.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/Gens.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/data/LinkDataSuite.scala
|-|-|
| Spec | https://opentelemetry.io/docs/specs/otel/trace/api/#link |
| Java implementation | [LinkData.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/data/LinkData.java) |
> sdk-trace: add `LinkData`

- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/data/StatusData.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/data/StatusDataSuite.scala
|-|-|
| Spec | https://opentelemetry.io/docs/specs/otel/trace/api/#set-status |
| Java implementation | [StatusData.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/data/StatusData.java) |
> trace sdk: add `StatusData`

- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/data/EventData.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/Cogens.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/Gens.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/data/EventDataSuite.scala
|-|-|
| Spec | https://opentelemetry.io/docs/specs/otel/trace/api/#add-events |
| Java implementation | [EventData.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/data/EventData.java) |
> [!NOTE]  
> An Event is structurally defined by the following properties:
> - Name of the event.
> - A timestamp for the event. Either the time at which the event was added or a custom timestamp provided by the user.
> - Zero or more [Attributes](https://opentelemetry.io/docs/specs/otel/common/#attribute) further describing the event.
> sdk-trace: add `EventData`

- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/IdGenerator.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/IdGeneratorSuite.scala
|-|-|
| Spec | https://opentelemetry.io/docs/specs/otel/trace/sdk/#id-generators |
| Java implementation | [IdGenerator.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/IdGenerator.java) <br> [RandomIdGenerator.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/RandomIdGenerator.java) |
> sdk-trace: add `IdGenerator`

- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/data/SpanData.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/Cogens.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/Gens.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/data/LinkDataSuite.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/data/SpanDataSuite.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/data/StatusDataSuite.scala
|-|-|
| Spec | https://opentelemetry.io/docs/specs/otel/trace/api/#span |
| Java implementation | [SpanData.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/data/SpanData.java) |
The last `*Data` model.
> sdk-trace: add `SpanData`

- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/IdGeneratorSuite.scala
The tests are timing out on JS and Native platforms occasionally.
> IdGeneratorSuite: reduce the number of attempts

- benchmarks/src/main/scala/org/typelevel/otel4s/benchmarks/AttributesBenchmark.scala
- build.sbt
- sdk/common/src/main/scala/org/typelevel/otel4s/sdk/Attributes.scala
- sdk/common/src/main/scala/org/typelevel/otel4s/sdk/Resource.scala
- sdk/common/src/main/scala/org/typelevel/otel4s/sdk/common/InstrumentationScope.scala
- sdk/common/src/test/scala/org/typelevel/otel4s/sdk/AttributesProps.scala
- sdk/common/src/test/scala/org/typelevel/otel4s/sdk/ResourceProps.scala
- sdk/common/src/test/scala/org/typelevel/otel4s/sdk/ResourceSuite.scala
- sdk/common/src/test/scala/org/typelevel/otel4s/sdk/common/InstrumentationScopeSuite.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/data/EventData.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/data/LinkData.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/Gens.scala
> Add `Builder` of `Attributes`. Documentation improvements

- sdk/common/src/main/scala/org/typelevel/otel4s/sdk/Resource.scala
- sdk/common/src/test/scala/org/typelevel/otel4s/sdk/ResourceProps.scala
- sdk/common/src/test/scala/org/typelevel/otel4s/sdk/ResourceSuite.scala
The changes:
1) Redefine `Resource` as a sealed trait
2) Update documentation
3) Rename `mergeInto` to `merge`
4) Rename `ResourceInitiationError` to `ResourceInitializationError`
> Redefine `Resource` as a sealed trait

- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/SpanProcessor.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/SpanRef.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/SpanProcessorSuite.scala
|-|-|
| Spec | https://opentelemetry.io/docs/specs/otel/trace/sdk/#span-processor |
| Java implementation | [SpanProcessor.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SpanProcessor.java) <br>  [ReadWriteSpan.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/ReadWriteSpan.java) <br> [ReadableSpan.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/ReadableSpan.java) |
Some `SpanProcessor`s may require access to the **internal** state of a span (e.g. actual name, SpanData, etc). The changes made to the span must be accessible by the processor. For example, we …
> sdk-trace: add `SpanProcessor`

- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/exporter/SpanExporter.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/exporter/InMemorySpanExporter.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/exporter/SpanExporterSuite.scala
|-|-|
| Spec | https://opentelemetry.io/docs/specs/otel/trace/sdk/#span-exporter |
| Java implementation | [SpanExporter.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/export/SpanExporter.java) |
Well, `Export` and `ForceFlush` are obvious. `Shutdown`, however, is more tricky. 
Since the CE offers flexible lifecycle management of resources, I see two options:
1) Each `SpanExporter`  should manage its lifecycle on its own:
```scala
def otlpHttpExporter: Resource[F, SpanExporter[F]] = ???
def otlpGrpcExporter: Resource[F, SpanExporter[F]] = ???
val exporter: Resource[F, SpanEporter[F]] = 
for {
otlpHttp <- otlpHttpExporter
otlpGrpc <- otlpGrpcExporter
} yield SpanExporter.of(otlpHttp, otlpGrpc)
``` …
> sdk-trace: add `SpanExporter`

- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/SpanProcessor.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/SpanProcessorSuite.scala
Follow up https://github.com/typelevel/otel4s/pull/374#discussion_r1405175860
> `SpanProcessor` - rethrow a composite failure on multiple errors

- build.sbt
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/SdkSpanBackend.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/data/SpanData.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/Cogens.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/Gens.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/SdkSpanBackendSuite.scala
|-|-|
| Java implementation | [SdkSpan.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkSpan.java) |
> sdk-trace: add `SdkSpanBackend`

- sdk/common/src/main/scala/org/typelevel/otel4s/sdk/context/Context.scala
- sdk/common/src/test/scala/org/typelevel/otel4s/sdk/context/ContextKeySuite.scala
- sdk/common/src/test/scala/org/typelevel/otel4s/sdk/context/ContextSuite.scala
|-|-|
| Spec | https://opentelemetry.io/docs/specs/otel/context |
| Java implementation | [Context.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/context/src/main/java/io/opentelemetry/context/Context.java) |
We will use this context to carry span details, etc.
> sdk-common: add `Context`

- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/samplers/ParentBasedSampler.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/samplers/Sampler.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/samplers/SamplingDecision.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/samplers/SamplingResult.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/samplers/TraceIdRatioBasedSampler.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/samplers/ParentBasedSamplerSuite.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/samplers/SamplerSuite.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/samplers/SamplingDecisionSuite.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/samplers/SamplingResultSuite.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/samplers/ShouldSampleInput.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/samplers/TraceIdRatioBasedSamplerSuite.scala
|-|-|
| Spec | https://opentelemetry.io/docs/specs/otel/trace/sdk/#sampler |
| Java implementation | [Sampler.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/samplers/Sampler.java) </br> [ParentBasedSampler.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/samplers/ParentBasedSampler.java) </br> [TraceIdRatioBasedSampler.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/samplers/TraceIdRatioBasedSampler.java) </br> [SamplingResult.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/samplers/Sam …
> trace sdk: add samplers

- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/SdkSpanBackend.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/SpanRef.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/processor/SimpleSpanProcessor.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/processor/SpanProcessor.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/SdkSpanBackendSuite.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/processor/SimpleSpanProcessorSuite.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/processor/SpanProcessorSuite.scala
|-|-|
| Spec | https://opentelemetry.io/docs/specs/otel/trace/sdk/#simple-processor |
| Java implementation | [SimpleSpanProcessor.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/export/SimpleSpanProcessor.java) |
I also moved `SpanProcessor` to the `org.typelevel.otel4s.sdk.trace.processor` package.
> sdk-trace: add `SimpleSpanProcessor`

- core/common/src/main/scala/org/typelevel/otel4s/AttributeKey.scala
Add `AttributeKey#apply` method that creates an `Attribute`.
Motivated by a desire to improve the ergonomics of semconv.
> Improve `Attribute` creation ergonomics

- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/SdkContextKeys.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/SdkTraceScope.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/SdkTraceScopeSuite.scala
There is no direct equivalent in the OpenTelemetry Java library. 
Even though the propagation logic is built on top of `cats.mtl.Local`, I want to encapsulate all context-manipulation operations in one place. It simplifies testing and allows us to provide well-defined documentation.
> sdk-trace: add `SdkTraceScope`

- benchmarks/src/main/scala/org/typelevel/otel4s/benchmarks/AttributesBenchmark.scala
- build.sbt
- core/common/src/main/scala/org/typelevel/otel4s/Attributes.scala
- core/common/src/test/scala/org/typelevel/otel4s/ArbitraryInstances.scala
- core/common/src/test/scala/org/typelevel/otel4s/AttributesLawTests.scala
- core/common/src/test/scala/org/typelevel/otel4s/AttributesProps.scala
- sdk/common/src/main/scala/org/typelevel/otel4s/sdk/Resource.scala
- sdk/common/src/main/scala/org/typelevel/otel4s/sdk/common/InstrumentationScope.scala
- sdk/common/src/test/scala/org/typelevel/otel4s/sdk/ArbitraryInstances.scala
- sdk/common/src/test/scala/org/typelevel/otel4s/sdk/AttributesLawTests.scala
- sdk/common/src/test/scala/org/typelevel/otel4s/sdk/AttributesProps.scala
- sdk/common/src/test/scala/org/typelevel/otel4s/sdk/common/InstrumentationScopeSuite.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/SdkSpanBackend.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/data/EventData.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/data/LinkData.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/data/SpanData.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/samplers/ParentBasedSampler.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/samplers/Sampler.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/samplers/SamplingResult.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/samplers/TraceIdRatioBasedSampler.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/Arbitraries.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/Cogens.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/Gens.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/SdkSpanBackendSuite.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/data/EventDataSuite.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/samplers/SamplingResultSuite.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/samplers/ShouldSampleInput.scala
> Move `Attributes` to core-common

- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/processor/BatchSpanProcessor.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/processor/BatchSpanProcessorSuite.scala
|-|-|
| Spec | https://opentelemetry.io/docs/specs/otel/trace/sdk/#batching-processor |
| Java implementation | [BatchSpanProcessor.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessor.java) |
> sdk-trace: add `BatchSpanProcessor`

- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/processor/SimpleSpanProcessor.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/NoopConsole.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/SdkSpanBackendSuite.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/processor/BatchSpanProcessorSuite.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/processor/SimpleSpanProcessorSuite.scala
Test logs are verbose and non-informative. We can silent them.
> Use no-op `cats.effect.std.Console` in tests

- core/metrics/src/main/scala/org/typelevel/otel4s/metrics/BucketBoundaries.scala
- core/metrics/src/main/scala/org/typelevel/otel4s/metrics/Histogram.scala
- core/metrics/src/main/scala/org/typelevel/otel4s/metrics/Meter.scala
- core/metrics/src/test/scala/org/typelevel/otel4s/metrics/BucketBoundariesSuite.scala
- oteljava/metrics/src/main/scala/org/typelevel/otel4s/oteljava/metrics/HistogramBuilderImpl.scala
- oteljava/metrics/src/main/scala/org/typelevel/otel4s/oteljava/metrics/MeterImpl.scala
|-|-|
| Spec | [Explicit bucket boundaries](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#instrument-advisory-parameter-explicitbucketboundaries)  |
| Java implementation | [LongHistogramBuilder.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/api/all/src/main/java/io/opentelemetry/api/metrics/LongHistogramBuilder.java) <br> [DoubleHistogramBuilder.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/api/all/src/main/java/io/opentelemetry/api/metrics/DoubleHistogramBuilder.java) |
> Histogram builder: add `withExplicitBucketBoundaries`

- sdk/common/src/main/scala/org/typelevel/otel4s/sdk/context/package.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/SdkSpanBackend.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/SdkSpanBuilder.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/SdkTraceScope.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/SdkTracer.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/SdkTracerBuilder.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/SdkTracerProvider.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/SpanRef.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/processor/SpanStorage.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/samplers/ParentBasedSampler.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/samplers/TraceIdRatioBasedSampler.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/SdkTracerSuite.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/SpanNode.scala
|-|-|
| Java implementation | [SdkTracer.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkTracer.java) <br> [SdkTracerBuilder.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkTracerBuilder.java) <br> [SdkTracerProvider.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkTracerProvider.java) <br> [SdkTracerProviderBuilder.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkTracerProviderBuilder.java) |
It's hard to add each of them individually, so we have a big PR 🙁
> sdk-trace: add `SdkTracer`, `SdkTracerBuilder`, `SdkTracerProvider`

- core/metrics/src/main/scala/org/typelevel/otel4s/metrics/Measurement.scala
- core/metrics/src/main/scala/org/typelevel/otel4s/metrics/ObservableMeasurement.scala
- core/metrics/src/test/scala/org/typelevel/otel4s/metrics/ObservableSuite.scala
- oteljava/common/src/main/scala/org/typelevel/otel4s/oteljava/Conversions.scala
- oteljava/metrics/src/main/scala/org/typelevel/otel4s/oteljava/metrics/ObservableDoubleImpl.scala
- oteljava/metrics/src/main/scala/org/typelevel/otel4s/oteljava/metrics/ObservableLongImpl.scala
- oteljava/metrics/src/test/scala/org/typelevel/otel4s/oteljava/metrics/ObservableSuite.scala
`Measurement` could be extended in the future. Dealing with a sealed trait rather than a case class would be easier.
> metrics: redefine `Measurement` as a sealed trait

- .github/workflows/ci.yml
- build.sbt
- scalafix/input/src/main/scala/example/V0_5_0Rewrites.scala
- scalafix/output/src/main/scala/example/V0_5_0Rewrites.scala
- scalafix/rules/src/main/resources/META-INF/services/scalafix.v1.Rule
- scalafix/rules/src/main/scala/org/typelevel/otel4s/scalafix/V0_5_0Rewrites.scala
- scalafix/tests/src/test/scala/org/typelevel/otel4s/scalafix/RuleSuite.scala
Closes #413.
Do we need to publish the rule as a separate jar? From what I see, Scala Steward should work with a reference to git too?
```hocon
migrations = [
{
groupId: "org.typelevel",
artifactIds: ["otel4s-.*"],
newVersion: "0.5.0",
rewriteRules: ["github:typelevel/otel4s/V0_5_0Rewrites?sha=v0.5.0"]
}
]
```
> Implement scalafix migration rules

- sdk/common/src/main/scala/org/typelevel/otel4s/sdk/autoconfigure/AutoConfigure.scala
- sdk/common/src/main/scala/org/typelevel/otel4s/sdk/autoconfigure/AutoConfigureError.scala
- sdk/common/src/main/scala/org/typelevel/otel4s/sdk/autoconfigure/Config.scala
- sdk/common/src/main/scala/org/typelevel/otel4s/sdk/autoconfigure/ConfigurationError.scala
- sdk/common/src/main/scala/org/typelevel/otel4s/sdk/autoconfigure/TelemetryResourceAutoConfigure.scala
- sdk/common/src/test/scala/org/typelevel/otel4s/sdk/autoconfigure/ConfigSuite.scala
- sdk/common/src/test/scala/org/typelevel/otel4s/sdk/autoconfigure/TelemetryResourceAutoConfigureSuite.scala
That's the first step towards an auto-configuration of the SDK module. 
OpenTelemetry Java also relies on the [SPI](https://docs.oracle.com/javase/tutorial/sound/SPI-intro.html), which is available only on the JVM (IIRC). https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md#resource-provider-spi.
How the `AutoConfigure` can be used in the SDK module:
https://github.com/typelevel/otel4s/blob/34a509247f8c6eb02b3a2f8745aa6d63946ac52e/sdk/all/src/main/scala/org/typelevel/otel4s/sdk/OpenTelemetrySdk.scala#L194-L205
> sdk: add `AutoConfigure` and `Config`

- core/trace/src/test/scala/org/typelevel/otel4s/trace/scalacheck/Gens.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/context/propagation/JaegerPropagator.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/context/propagation/JaegerPropagatorSuite.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/context/propagation/W3CTraceContextPropagatorSuite.scala
|-|-|
| Spec | https://www.jaegertracing.io/docs/client-libraries/#propagation-format |
| Java implementation | [JaegerPropagator.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/JaegerPropagator.java) |
> sdk-trace: add `JaegerPropagator`

- sdk/common/src/main/scala/org/typelevel/otel4s/sdk/autoconfigure/AutoConfigure.scala
- sdk/common/src/main/scala/org/typelevel/otel4s/sdk/autoconfigure/AutoConfigureError.scala
- sdk/common/src/main/scala/org/typelevel/otel4s/sdk/autoconfigure/Config.scala
- sdk/common/src/main/scala/org/typelevel/otel4s/sdk/autoconfigure/TelemetryResourceAutoConfigure.scala
- sdk/common/src/test/scala/org/typelevel/otel4s/sdk/autoconfigure/AutoConfigureErrorSuite.scala
- sdk/common/src/test/scala/org/typelevel/otel4s/sdk/autoconfigure/AutoConfigureSuite.scala
- sdk/common/src/test/scala/org/typelevel/otel4s/sdk/autoconfigure/ConfigSuite.scala
Thay way we can provide meaningful reason why the component cannot be autoconfigured.
> sdk-common: `AutoConfigure` - use config keys in the error message

- benchmarks/src/main/scala/org/typelevel/otel4s/benchmarks/TraceBenchmark.scala
- core/common/src/main/scala/org/typelevel/otel4s/context/LocalProvider.scala
- core/common/src/test/scala/org/typelevel/otel4s/context/LocalProviderSuite.scala
- docs/customization/histogram-custom-buckets/README.md
- docs/examples/grafana/README.md
- docs/examples/honeycomb/README.md
- docs/examples/jaeger-docker/README.md
- docs/tracing-context-propagation.md
- examples/src/main/scala/HistogramBucketsExample.scala
- examples/src/main/scala/ObservableExample.scala
- examples/src/main/scala/TraceExample.scala
- examples/src/main/scala/TracingExample.scala
- oteljava/all/src/main/scala/org/typelevel/otel4s/oteljava/OtelJava.scala
- oteljava/common/src/main/scala/org/typelevel/otel4s/oteljava/context/package.scala
Follow-up to https://github.com/typelevel/otel4s/pull/420#discussion_r1440718674.
Currently, there is no way to provide an arbitrary `IOLocal` or `Local` instance to certain `OtelJava` methods. 
For example, you cannot use `OtelJava.resource` with an arbitrary `IOLocal` instance. 
Why would you want to use a custom `IOLocal`?  To have direct access to the `Context` and keep the benefits of the `resource` API. For example, https://github.com/typelevel/otel4s/issues/431#issuecomment-1890758408.
1) `LocalProvider` is kinda a magic implicit. The derivation logic may be confusing for newcomers
2) In some cases, the explicit type must be provided (e.g. `OtelJava.autoConfigured[IO]()`).
_____
The `LocalProvider` has usages beyond `OtelJava`. It fits nicely into the SDK module too: …
> Add `LocalProvider`

- build.sbt
- sdk-exporter/common/.js/src/test/scala/org/typelevel/otel4s/sdk/exporter/SuiteRuntimePlatform.scala
- sdk-exporter/common/.jvm/src/test/scala/org/typelevel/otel4s/sdk/exporter/SuiteRuntimePlatform.scala
- sdk-exporter/common/.native/src/test/scala/org/typelevel/otel4s/sdk/exporter/SuiteRuntimePlatform.scala
- sdk-exporter/common/src/main/scala/org/typelevel/otel4s/sdk/exporter/otlp/OtlpHttpClient.scala
- sdk-exporter/common/src/main/scala/org/typelevel/otel4s/sdk/exporter/otlp/autoconfigure/OtlpHttpClientAutoConfigure.scala
- sdk-exporter/common/src/test/scala/org/typelevel/otel4s/sdk/exporter/otlp/autoconfigure/OtlpHttpClientAutoConfigureSuite.scala
- sdk-exporter/trace/shared/src/main/scala/org/typelevel/otel4s/sdk/exporter/otlp/trace/OtlpHttpSpanExporter.scala
- sdk-exporter/trace/shared/src/test/scala/org/typelevel/otel4s/sdk/exporter/otlp/trace/OtlpHttpSpanExporterSuite.scala
- sdk/common/src/main/scala/org/typelevel/otel4s/sdk/autoconfigure/Config.scala
The usage (from the upcoming PR):
https://github.com/typelevel/otel4s/blob/af028a07e6c0c6243f944182554282be3f1a2a4f/sdk-exporter/trace/shared/src/main/scala/org/typelevel/otel4s/sdk/exporter/otlp/trace/autoconfigure/OtlpSpanExporterAutoConfigure.scala#L95-L98
The preview version of the autoconfigure feature is available here https://github.com/typelevel/otel4s/pull/325.
> sdk-exporter-trace: add `OtlpHttpClientAutoConfigure`

- core/metrics/src/main/scala/org/typelevel/otel4s/metrics/BatchCallback.scala
- core/metrics/src/main/scala/org/typelevel/otel4s/metrics/Meter.scala
- core/metrics/src/main/scala/org/typelevel/otel4s/metrics/ObservableCounter.scala
- core/metrics/src/main/scala/org/typelevel/otel4s/metrics/ObservableGauge.scala
- core/metrics/src/main/scala/org/typelevel/otel4s/metrics/ObservableMeasurement.scala
- core/metrics/src/main/scala/org/typelevel/otel4s/metrics/ObservableUpDownCounter.scala
- core/metrics/src/test/scala/org/typelevel/otel4s/metrics/ObservableSuite.scala
- oteljava/metrics/src/main/scala/org/typelevel/otel4s/oteljava/metrics/BatchCallbackImpl.scala
- oteljava/metrics/src/main/scala/org/typelevel/otel4s/oteljava/metrics/MeterImpl.scala
- oteljava/metrics/src/main/scala/org/typelevel/otel4s/oteljava/metrics/ObservableCounterBuilderImpl.scala
- oteljava/metrics/src/main/scala/org/typelevel/otel4s/oteljava/metrics/ObservableGaugeBuilderImpl.scala
- oteljava/metrics/src/main/scala/org/typelevel/otel4s/oteljava/metrics/ObservableMeasurementImpl.scala
- oteljava/metrics/src/main/scala/org/typelevel/otel4s/oteljava/metrics/ObservableUpDownCounterBuilderImpl.scala
- oteljava/metrics/src/test/scala/org/typelevel/otel4s/oteljava/metrics/BatchCallbackSuite.scala
Closes #201.
Nearly identical to what OpenTelemetry Java offers.
```scala
val meter: Meter[F] = ???
val background: Resource[F, Unit] = 
for {
counter <- Resource.eval(meter.observableCounter[Long]("counter").createObserver)
upDownCounter <- Resource.eval(meter.observableUpDownCounter[Double]("up-down-counter").createObserver)
gauge <- Resource.eval(meter.observableGauge[Double]("gauge").createObserver)
_ <- meter.batchCallback(
callback = counter.record(1L) *> upDownCounter.record(2.0) *> gauge.record(3.0),
counter,
upDownCounter,
gauge
)
} yield ()
```
A typesafe alternative with arity up to 9 arguments. It's much harder to miss an instrument that way. 
```scala
val meter: Meter[F] = ???
val background: Resource[F, Unit] = meter.batchCallback.of( …
```
> metrics: add `Meter[F].batchCallback`

- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/SdkTracerProvider.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/autoconfigure/SpanExportersAutoConfigure.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/autoconfigure/SpanExportersAutoConfigureSuite.scala
Due to modularity and lack of [SPI](https://docs.oracle.com/javase/tutorial/sound/SPI-intro.html) on Native/Scala.js platforms, I came up with the following solution:
```scala
OpenTelemetrySdk
.autoConfigured(
_.addExporterConfigurer(OtlpSpanExporterAutoConfigure[IO]) // add the external configurer here
)
.use { autoConfigured =>
val sdk = autoConfigured.sdk
for {
tracer <- sdk.tracerProvider.get("my-tracer")
_ <- tracer
.span("test", Attribute("test", "test123"))
.use(sd => IO.println(sd.context))
} yield ()
}
```
The SDK autoconfigure will be able to:
1) Configure the telemetry resource
2) Configure the tracer provider (batch span processor, etc)
3) Configure sampler
4) Partially configure span exporter (the external exporters must be registered manually)
> sdk-trace: add `SpanExportersAutoConfigure`

- core/trace/src/main/scala/org/typelevel/otel4s/trace/TracerProvider.scala
- sdk/common/src/main/scala/org/typelevel/otel4s/sdk/autoconfigure/CommonConfigKeys.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/SdkTraces.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/SdkTracesSuite.scala
`SdkTraces` provides a handy way to load the SDK tracing module:
```scala
SdkTraces.autoConfigured[IO]().use { traces =>
val provider = traces.tracerProvider
...
}
```
> sdk-trace: add `SdkTraces`

- core/metrics/src/main/scala-2/org/typelevel/otel4s/metrics/CounterMacro.scala
- core/metrics/src/main/scala-2/org/typelevel/otel4s/metrics/HistogramMacro.scala
- core/metrics/src/main/scala-2/org/typelevel/otel4s/metrics/UpDownCounterMacro.scala
- core/metrics/src/main/scala-3/org/typelevel/otel4s/metrics/CounterMacro.scala
- core/metrics/src/main/scala-3/org/typelevel/otel4s/metrics/HistogramMacro.scala
- core/metrics/src/main/scala-3/org/typelevel/otel4s/metrics/UpDownCounterMacro.scala
- core/metrics/src/main/scala/org/typelevel/otel4s/metrics/Counter.scala
- core/metrics/src/main/scala/org/typelevel/otel4s/metrics/Histogram.scala
- core/metrics/src/main/scala/org/typelevel/otel4s/metrics/UpDownCounter.scala
- core/metrics/src/test/scala/org/typelevel/otel4s/metrics/CounterSuite.scala
- core/metrics/src/test/scala/org/typelevel/otel4s/metrics/HistogramSuite.scala
- core/metrics/src/test/scala/org/typelevel/otel4s/metrics/UpDownCounterSuite.scala
- core/trace/src/main/scala-2/org/typelevel/otel4s/trace/SpanMacro.scala
- core/trace/src/main/scala-2/org/typelevel/otel4s/trace/TracerMacro.scala
- core/trace/src/main/scala-3/org/typelevel/otel4s/trace/SpanMacro.scala
- core/trace/src/main/scala-3/org/typelevel/otel4s/trace/TracerMacro.scala
- core/trace/src/main/scala/org/typelevel/otel4s/trace/Span.scala
- core/trace/src/main/scala/org/typelevel/otel4s/trace/SpanBuilder.scala
- core/trace/src/main/scala/org/typelevel/otel4s/trace/SpanFinalizer.scala
- core/trace/src/test/scala/org/typelevel/otel4s/trace/TracerSuite.scala
- oteljava/metrics/src/main/scala/org/typelevel/otel4s/oteljava/metrics/CounterBuilderImpl.scala
- oteljava/metrics/src/main/scala/org/typelevel/otel4s/oteljava/metrics/HistogramBuilderImpl.scala
- oteljava/metrics/src/main/scala/org/typelevel/otel4s/oteljava/metrics/UpDownCounterBuilderImpl.scala
- oteljava/trace/src/main/scala/org/typelevel/otel4s/oteljava/trace/SpanBackendImpl.scala
- oteljava/trace/src/main/scala/org/typelevel/otel4s/oteljava/trace/SpanBuilderImpl.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/SdkSpanBackend.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/SdkSpanBuilder.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/SdkSpanBackendSuite.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/processor/SimpleSpanProcessorSuite.scala
Add overloads of `Attribute[_]` varargs methods that accept `immutable.Iterable[Attribute[_]]`, to support use of `Attributes`.
> Enhance core APIs to support `Attributes`

- build.sbt
- oteljava/testkit/src/main/scala/org/typelevel/otel4s/oteljava/testkit/OtelJavaTestkit.scala
- oteljava/trace-testkit/src/main/scala/org/typelevel/otel4s/oteljava/testkit/trace/TracesTestkit.scala
A compound instance that provides in-memory metric- and tracer- providers.
> oteljava-testkit: add `OtelJavaTestkit`

- build.sbt
- core/metrics/src/main/scala/org/typelevel/otel4s/metrics/MeterProvider.scala
- sdk/all/src/main/scala/org/typelevel/otel4s/sdk/OpenTelemetrySdk.scala
- sdk/all/src/test/scala/org/typelevel/otel4s/sdk/OpenTelemetrySdkSuite.scala
`OpenTelemetrySdk` can be autoconfigured:
```scala
OpenTelemetrySdk.autoConfigured[IO]().use { autoConfigured =>
val provider = autoConfigured.sdk.tracerProvider
...
}
```
> sdk - add `OpenTelemetrySdk`

- core/common/src/main/scala/org/typelevel/otel4s/AttributeKey.scala
Use case: code that adds a prefix to all the names in a `Seq[Attribute[_]]`.  ``Attribute.apply(prefix + old.name, old.`type`)`` won't work, because there is no access to `KeySelect[A]`.
> Add transformName to Attribute

- core/common/src/test/scala/org/typelevel/otel4s/AttributesProps.scala
- core/common/src/test/scala/org/typelevel/otel4s/scalacheck/Gens.scala
- core/metrics/src/main/scala/org/typelevel/otel4s/metrics/Measurement.scala
- core/metrics/src/main/scala/org/typelevel/otel4s/metrics/ObservableMeasurement.scala
- oteljava/common-testkit/src/main/scala/org/typelevel/otel4s/oteljava/testkit/Conversions.scala
- sdk-exporter/trace/src/test/scala/org/typelevel/otel4s/sdk/exporter/otlp/trace/OtlpHttpSpanExporterSuite.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/SdkSpanBackend.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/SdkSpanBuilder.scala
As @NthPortal pointed out, `.to(Attributes)` is more idiomatic.
> Use `.to(Attributes)` instead of `.fromSpecific`

- examples/src/main/scala/SdkTracingExample.scala
- sdk/all/src/main/scala/org/typelevel/otel4s/sdk/OpenTelemetrySdk.scala
- sdk/all/src/test/scala/org/typelevel/otel4s/sdk/OpenTelemetrySdkSuite.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/SdkTraces.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/autoconfigure/SpanExportersAutoConfigure.scala
Both metrics and tracing modules have separate exporters. We need to registered confiugrers for both of them.
To make things clear, it is better to distinguish names. 
So once the metrics module is ready, we will have:
```scala
trait Builder[F[_]] {
def addSpanExporterConfigurer(configurer: AutoConfigure.Named[F, SpanExporter[F]]): Builder[F]
def addMetricExporterConfigurer(configurer: AutoConfigure.Named[F, MetricExporter[F]]): Builder[F]
}
```
> OpenTelemetrySdk: rename `addExporterConfigurer` to `addSpanExporterConfigurer`

- core/common/src/main/scala/org/typelevel/otel4s/Attribute.scala
- core/common/src/main/scala/org/typelevel/otel4s/AttributeKey.scala
- core/common/src/main/scala/org/typelevel/otel4s/Attributes.scala
- core/common/src/test/scala/org/typelevel/otel4s/scalacheck/Gens.scala
- core/metrics/src/main/scala/org/typelevel/otel4s/metrics/Histogram.scala
OpenTelemetry Java [encourages](https://github.com/open-telemetry/opentelemetry-java/blob/main/api/all/src/main/java/io/opentelemetry/api/common/AttributesBuilder.java#L44-L45) preallocating attribute keys and reusing them later.
For example:
```scala
class JobProcessor[F[_]]
object JobProcessor {
object AttributeKeys {
val ExecutionLatency: AttributeKey[Double] = AttributeKey("job.processor.execution.latency")
}
}
```
1) `KeySelect` belongs more to the `AttributeKey` rather than `Attribute`
2) We can provide a generic `AttributeKey.apply`: `AttributeKey[Double]("key")` vs `AttributeKey.double("key")`
3) For most users, the migration should be seamless
WDYT?
> Move `KeySelect` to `AttributeKey`

- sdk/all/src/main/scala/org/typelevel/otel4s/sdk/OpenTelemetrySdk.scala
- sdk/all/src/test/scala/org/typelevel/otel4s/sdk/OpenTelemetrySdkSuite.scala
- sdk/common/src/main/scala/org/typelevel/otel4s/sdk/autoconfigure/TelemetryResourceAutoConfigure.scala
- sdk/common/src/test/scala/org/typelevel/otel4s/sdk/autoconfigure/TelemetryResourceAutoConfigureSuite.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/SdkTracesSuite.scala
We should use the default TelemetryResource as an initial one. Otherwise, mandatory build-time information (library version, etc) is missing.
OpenTelemetry Java has identical logic: https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/ResourceConfiguration.java#L88.
> sdk: use `TelemetryResource.default` as an initial resource

- core/common/src/main/scala/org/typelevel/otel4s/Attributes.scala
- core/common/src/test/scala/org/typelevel/otel4s/AttributesProps.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/SdkSpanBackendSuite.scala
Disallow having multiple `Attribute`s with the same name, even if they are of different types.
Simplify `Attributes` by no longer having its API treat it like a map—rename `updated` to `added`, make `toMap` package private, and remove the following methods:
`contains`, `removed`, `-`, `removedAll`, `--`, `keys`
Fixes #513
Alternative (that I prefer) to #515
> Partially redesign `Attributes`

- .github/workflows/ci.yml
- build.sbt
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/data/AggregationTemporality.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/data/AggregationTemporalitySuite.scala
|-|-|
| Spec | https://opentelemetry.io/docs/specs/otel/metrics/data-model/#temporality |
| Java implementation | [AggregationTemporality.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/data/AggregationTemporality.java) |
Starting shaping `sdk-metrics` module. There is a working [prototype](https://github.com/iRevive/otel4s/pull/4/files).
> sdk-metrics: add `AggregationTemporality`

- README.md
- build.sbt
- docs/directory.conf
- docs/index.md
- docs/sdk/configuration.md
- docs/sdk/directory.conf
- docs/sdk/overview.md
Starting with the `Overview` and `Configuration` sections.
> site: add SDK section

- build.sbt
`sdk` depends on the `sdk-metrics` and the `sdk-metrics` artifact is required.
But `sdk-metrics` will not be published soon. 
https://discord.com/channels/632277896739946517/1093154207328108634/1221385839435583499
> remove `sdk-metrics` dependency from the `sdk`

- oteljava/all/src/main/scala/org/typelevel/otel4s/oteljava/OtelJava.scala
- sdk/all/src/main/scala/org/typelevel/otel4s/sdk/OpenTelemetrySdk.scala
> oteljava: add `OtelJava.noop`

- build.sbt
- core/metrics/src/main/scala/org/typelevel/otel4s/metrics/BucketBoundaries.scala
- core/metrics/src/test/scala/org/typelevel/otel4s/metrics/BucketBoundariesSuite.scala
`Hash` and `Show` will be utilized in the upcoming metrics SDK.
> core-metrics: add `Hash` and `Show` for `BucketBoundaries`

- build.sbt
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/data/TimeWindow.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/data/TimeWindowSuite.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/scalacheck/Arbitraries.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/scalacheck/Cogens.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/scalacheck/Gens.scala
There is no direct equivalent in the OpenTelemetry Java. The `TimeWindow` will be actively used in the SDK module, for example in the [data points](https://github.com/iRevive/otel4s/pull/4/files#diff-d8444dbbfdcddec27a953cc4f7d2b5f88e5e8f8d7a81f85198dacab3acfd5ecf).
> sdk-metrics: add `TimeWindow`

- core/trace/src/main/scala/org/typelevel/otel4s/trace/Tracer.scala
- core/trace/src/test/scala/org/typelevel/otel4s/trace/BaseTracerSuite.scala
- oteljava/trace/src/main/scala/org/typelevel/otel4s/oteljava/trace/TracerImpl.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/SdkTracer.scala
The motivation for this is that we had an issue with tracing being missing at $work due to a bug (which was my fault), but it took some time to notice that tracing was missing. the bug might have been discovered immediately if it had raised an error rather than silently doing nothing
> Add `Tracer#currentSpanOrThrow`

- build.sbt
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/data/ExemplarData.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/data/ExemplarDataSuite.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/scalacheck/Arbitraries.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/scalacheck/Cogens.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/scalacheck/Gens.scala
|-|-|
| Spec | https://opentelemetry.io/docs/specs/otel/metrics/data-model/#exemplars |
| Java implementation | [ExemplarData.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/data/ExemplarData.java) <br> [LongExemplarData.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/data/LongExemplarData.java) <br> [DoubleExemplarData.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/data/DoubleExemplarData.java) |
> sdk-metrics: add `ExemplarData`

- buildscripts/semantic-convention/templates/SemanticAttributes.scala.j2
- core/common/src/main/scala/org/typelevel/otel4s/AttributeKey.scala
- core/common/src/main/scala/org/typelevel/otel4s/AttributeType.scala
- core/common/src/test/scala/org/typelevel/otel4s/scalacheck/Cogens.scala
- core/common/src/test/scala/org/typelevel/otel4s/scalacheck/Gens.scala
- oteljava/common/src/main/scala/org/typelevel/otel4s/oteljava/AttributeConverters.scala
- oteljava/common/src/test/scala/org/typelevel/otel4s/oteljava/AttributeConvertersSuite.scala
- sdk-exporter/common/src/main/scala/org/typelevel/otel4s/sdk/exporter/otlp/ProtoEncoder.scala
- sdk-exporter/common/src/test/scala/org/typelevel/otel4s/sdk/exporter/otlp/JsonCodecs.scala
- sdk-exporter/common/src/test/scala/org/typelevel/otel4s/sdk/exporter/otlp/ProtoEncoderSuite.scala
- sdk-exporter/trace/src/test/scala/org/typelevel/otel4s/sdk/exporter/otlp/trace/OtlpHttpSpanExporterSuite.scala
- semconv/src/main/scala/org/typelevel/otel4s/semconv/resource/attributes/ResourceAttributes.scala
- semconv/src/main/scala/org/typelevel/otel4s/semconv/trace/attributes/SemanticAttributes.scala
> Widen `List` `AttributeType`s to `Seq`

- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/InstrumentType.scala
|-|-|
| Spec | https://opentelemetry.io/docs/specs/otel/metrics/api/#synchronous-and-asynchronous-instruments |
| Java implementation | [InstrumentType.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/InstrumentType.java) |
> sdk-metrics: add `InstrumentType`

- docs/examples/grafana/README.md
> docs: use `otlp/jaeger` exporter in the 'Grafana - All-in-one' example

- build.sbt
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/internal/InstrumentDescriptor.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/internal/InstrumentDescriptorSuite.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/scalacheck/Arbitraries.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/scalacheck/Cogens.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/scalacheck/Gens.scala
|-|-|
| Java implementation | [InstrumentDescriptor.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/descriptor/InstrumentDescriptor.java) |
`InstrumentDescriptor` will be used to associate an instrument with the measurements.
> sdk-metrics: add `InstrumentDescriptor`

- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/data/PointData.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/data/PointDataSuite.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/scalacheck/Arbitraries.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/scalacheck/Cogens.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/scalacheck/Gens.scala
|-|-|
| Spec | https://opentelemetry.io/docs/specs/otel/metrics/data-model/#metric-points |
| Java implementation | [PointData.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/data/PointData.java) <br> [DoublePointData.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/data/DoublePointData.java) <br> [LongPointData.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/data/LongPointData.java) <br> [HistogramPointData.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/data/HistogramPo …
> sdk-metrics: add `PointData`

- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/view/InstrumentSelector.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/scalacheck/Arbitraries.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/scalacheck/Cogens.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/scalacheck/Gens.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/view/InstrumentSelectorSuite.scala
|-|-|
| Java implementation | [InstrumentSelector.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/InstrumentSelector.java) |
`InstrumentSelector` is public. A user can utilize it to configure a view for a matching instrument. A view allows customizing aggregation strategy, the name of the instrument, etc.
> sdk-metrics: add `InstrumentSelector`

- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/view/AttributesProcessor.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/view/AttributesProcessorSuite.scala
|-|-|
| Java implementation | [AttributesProcessor.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/view/AttributesProcessor.java) |
| JavaScript implementation | [AttributesProcessor.ts](https://github.com/open-telemetry/opentelemetry-js/blob/main/packages/sdk-metrics/src/view/AttributesProcessor.ts) |
The class is internal and not supposed to be used publicly.
> sdk-metrics: add `AttributesProcessor`

- core/trace/src/main/scala-2/org/typelevel/otel4s/trace/SpanMacro.scala
- core/trace/src/main/scala-3/org/typelevel/otel4s/trace/SpanMacro.scala
- core/trace/src/main/scala/org/typelevel/otel4s/trace/Span.scala
- oteljava/trace/src/main/scala/org/typelevel/otel4s/oteljava/trace/SpanBackendImpl.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/SdkSpanBackend.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/SdkSpanBackendSuite.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/processor/SimpleSpanProcessorSuite.scala
`Span#addLink` is now stable:
https://github.com/open-telemetry/opentelemetry-specification/pull/3887
https://github.com/open-telemetry/opentelemetry-java/pull/6317
> trace: add `addLink` to `Span`

- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/data/MetricPoints.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/data/MetricPointsSuite.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/scalacheck/Arbitraries.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/scalacheck/Cogens.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/scalacheck/Gens.scala
|-|-|
| Java implementation | [Data.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/data/Data.java) <br> [SumData.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/data/SumData.java) <br> [GaugeData.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/data/GaugeData.java) <br> [HistogramData.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/data/HistogramData.java) |
> sdk-metrics: add `MetricPoints`

- docs/examples/honeycomb/README.md
Thanks for providing this example! I have suggestions on how to use Honeycomb, since that's my job.
I got some questions today about the data in Honeycomb from this library; the metrics are confusing. It is clearer when they are in their own dataset, so the schema is separate. You can query all datasets in an environment together, so they're still linked to the spans.
It used to be that all the data for Production belonged in one dataset, but then we added this Environments concept. So here's a suggestion for the docs.
> docs: advice on Honeycomb environments and datasets

- build.sbt
- docs/index.md
Follow-up https://github.com/typelevel/otel4s/pull/577#discussion_r1558010471.
> Docs: separate Scala 2 / Scala 3 examples of the no-op tracer

- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/Aggregation.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/AggregationSuite.scala
|-|-|
| Spec | https://opentelemetry.io/docs/specs/otel/metrics/sdk/#aggregation |
| Java implementation | [Aggregation.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/Aggregation.java) |
Unlike otel-java, we will split `Aggregation` and [Aggregator](https://github.com/iRevive/otel4s/blob/e5c1d041f4a7b025ee264c2358996f9e3a6031b1/sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/aggregation/Aggregator.scala). In other words, `Aggregation` defines only the aggregation strategy, and that's it. 
P.S. `Base2ExponentialBucketHistogram` is missing because I haven't implemented an aggregator for this strategy yet. I will add it later.
> sdk-metrics: add `Aggregation`

- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/data/ExemplarData.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/exemplar/ExemplarFilter.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/exemplar/TraceContextLookup.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/exemplar/ExemplarFilterSuite.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/scalacheck/Gens.scala
|-|-|
| Spec | https://opentelemetry.io/docs/specs/otel/metrics/sdk/#exemplarfilter |
| Java implementation | [ExemplarFilter.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/exemplar/ExemplarFilter.java) |
> sdk-metrics: add `ExemplarFilter` and `TraceContextLookup`

- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/exporter/AggregationTemporalitySelector.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/exporter/AggregationTemporalitySelectorSuite.scala
|-|-|
| Spec | https://opentelemetry.io/docs/specs/otel/metrics/sdk/#metricreader |
| Java implementation | [AggregationTemporalitySelector.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/export/AggregationTemporalitySelector.java)  |
The selector is required by the upcoming `MetricReader`.
> sdk-metrics: add `AggregationTemporalitySelector`

- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/data/MetricData.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/data/MetricDataSuite.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/scalacheck/Arbitraries.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/scalacheck/Cogens.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/scalacheck/Gens.scala
|-|-|
| Spec | https://opentelemetry.io/docs/specs/otel/metrics/data-model/#timeseries-model|
| Java implementation | [MetricData.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/data/MetricData.java) |
> sdk-metrics: add `MetricData`

- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/exporter/AggregationSelector.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/exporter/AggregationSelectorSuite.scala
|-|-|
| Spec | https://opentelemetry.io/docs/specs/otel/metrics/sdk/#metricreader |
| Java implementation | [DefaultAggregationSelector.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/export/DefaultAggregationSelector.java)  |
The selector is required by the upcoming `MetricReader`.
> sdk-metrics: add `AggregationSelector`

- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/exporter/CardinalityLimitSelector.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/exporter/CardinalityLimitSelectorSuite.scala
|-|-|
| Spec | https://opentelemetry.io/docs/specs/otel/metrics/sdk/#metricreader |
| Java implementation | [CardinalityLimitSelector.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/export/CardinalityLimitSelector.java)  |
The selector is required by the upcoming `MetricReader`.
> sdk-metrics: add `CardinalityLimitSelector`

- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/view/View.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/view/ViewSuite.scala
|-|-|
| Spec | https://opentelemetry.io/docs/specs/otel/metrics/sdk/#view |
| Java implementation | [View.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/View.java) |
> sdk-metrics: add `View`

- build.sbt
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/exemplar/CellSelector.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/exemplar/Exemplar.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/exemplar/ExemplarReservoir.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/exemplar/ReservoirCell.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/internal/utils/Adder.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/exemplar/ExemplarReservoirSuite.scala
|-|-|
| Spec | https://opentelemetry.io/docs/specs/otel/metrics/sdk/#exemplarreservoir |
| Java implementation | [ExemplarReservoir.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/exemplar/ExemplarReservoir.java) <br> [HistogramExemplarReservoir.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/exemplar/HistogramExemplarReservoir.java) <br> [FixedSizeExemplarReservoir.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/exemplar/FixedSizeExemplarReservoir.java) <br> …
> sdk-metrics: add `ExemplarReservoir`, `Exemplar`

- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/aggregation/Aggregator.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/aggregation/Target.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/internal/AsynchronousMeasurement.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/internal/MetricDescriptor.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/aggregation/TargetSuite.scala
|-|-|
| Spec | https://opentelemetry.io/docs/specs/otel/metrics/sdk/#aggregation |
There two basic traits for `Asynchronous` and `Synchronous` aggregators.
> sdk-metrics: add `Aggregator`

- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/aggregation/Aggregator.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/aggregation/SumAggregator.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/aggregation/SumAggregatorSuite.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/scalacheck/Gens.scala
|-|-|
| Spec | https://opentelemetry.io/docs/specs/otel/metrics/sdk/#sum-aggregation |
| Java implementation | [LongSumAggregator.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/aggregator/LongSumAggregator.java)  |
> sdk-metrics: add `SumAggregator`

- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/exporter/MetricExporter.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/exporter/MetricExporterSuite.scala
|-|-|
| Spec | https://opentelemetry.io/docs/specs/otel/metrics/sdk/#metricexporter |
| Java implementation | [MetricExporter.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/export/MetricExporter.java)  |
> sdk-metrics: add `MetricExporter`

- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/aggregation/ExplicitBucketHistogramAggregator.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/aggregation/ExplicitBucketHistogramAggregatorSuite.scala
|-|-|
| Spec | https://opentelemetry.io/docs/specs/otel/metrics/sdk/#explicit-bucket-histogram-aggregation |
| Java implementation | [ExplicitBucketHistogramAggregation.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/view/ExplicitBucketHistogramAggregation.java)  |
> sdk-metrics: add `ExplicitBucketHistogramAggregator`

- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/Aggregation.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/aggregation/Aggregator.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/aggregation/ExplicitBucketHistogramAggregator.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/aggregation/SumAggregator.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/aggregation/AggregatorSuite.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/scalacheck/Gens.scala
The `Aggregator` encapsulates the selection of the aggregator behind `synchronous` and `asynchronous` methods.
> sdk-metrics: add `Aggregator.synchronous` and `Aggregator.asynchronous`

- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/exporter/MetricProducer.scala
|-|-|
| Spec | https://opentelemetry.io/docs/specs/otel/metrics/sdk/#metricproducer |
| Java implementation | [MetricProducer.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/export/MetricProducer.java)  |
> sdk-metrics: add `MetricProducer`

- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/exporter/MetricExporter.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/exporter/MetricReader.scala
|-|-|
| Spec | https://opentelemetry.io/docs/specs/otel/metrics/sdk/#metricreader |
| Java implementation | [MetricReader.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/export/MetricReader.java)  |
> sdk-exporter: add `MetricReader`

- sdk/common/src/main/scala/org/typelevel/otel4s/sdk/internal/ComponentRegistry.scala
- sdk/common/src/test/scala/org/typelevel/otel4s/sdk/internal/ComponentRegistrySuite.scala
|-|-|
| Spec | https://opentelemetry.io/docs/specs/otel/trace/api/#get-a-tracer |
| Java implementation | [ComponentRegistry.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/common/src/main/java/io/opentelemetry/sdk/internal/ComponentRegistry.java) |
The use cases:
1) we need `ComponentRegistry` to keep `Meter`s unique
2) we need access to **all** instruments registered within SDK - see https://github.com/iRevive/otel4s/pull/4/files#diff-69173f42493b6c306e7ea1f016463b66dee4de03bd3e1c32951d23e9b8a2848dR268-R279
> sdk-common: add `ComponentRegistry`

- sdk/common/src/test/scala/org/typelevel/otel4s/sdk/test/InMemoryConsole.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/exporter/MetricReader.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/exporter/PeriodicMetricReader.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/exporter/InMemoryMetricExporter.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/exporter/PeriodicMetricReaderSuite.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/exporter/LoggingSpanExporterSuite.scala
|-|-|
| Spec | https://opentelemetry.io/docs/specs/otel/metrics/sdk/#periodic-exporting-metricreader |
| Java implementation | [PeriodicMetricReader.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/export/PeriodicMetricReader.java)  |
> sdk-metrics: add `PeriodMetricReader`

- core/trace/src/main/scala/org/typelevel/otel4s/trace/Span.scala
- oteljava/trace/src/main/scala/org/typelevel/otel4s/oteljava/trace/SpanBackendImpl.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/SdkSpanBackend.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/processor/SimpleSpanProcessorSuite.scala
Closes #204.
A few points:
1) How many people need to implement their own `Backend`? It's less relevant since we have an `sdk-trace` module.
2) Initially, `Span` had no public `end` API. The lifecycle has been managed automatically. So the `Backend#end` was private to prevent a user from ending a span by calling `backend.end`. Currently, `Span` has a public `end` API, so I don't think we should keep `Backend#end` private too.
> core-trace: make `Backend#end` public

- build.sbt
- sdk-exporter/trace/src/main/scala/org/typelevel/otel4s/sdk/exporter/otlp/trace/OtlpHttpSpanExporter.scala
The follow-up to https://github.com/typelevel/otel4s/pull/578.
I added `withClient` to the `BuilderImpl` class but forgot to add it to the `Builder` trait.
> sdk-exporter-trace: add `OtlpHttpSpanExporter.Builder#withClient`

- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/NoopInstrumentBuilder.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/NoopInstrumentBuilderSuite.scala
The validation happens in the [SdkMeter](https://github.com/iRevive/otel4s/blob/721c869c436c0f68d5cddf911f07e98d721fdace/sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/SdkMeter.scala#L42-L48).
> sdk-metrics: add `NoopInstrumentBuilder`

- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/SdkCounter.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/SdkCounterSuite.scala
|-|-|
| Spec | https://opentelemetry.io/docs/specs/otel/metrics/api/#counter |
| Java implementation | [SdkLongCounter.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkLongCounter.java)  |
> sdk-metrics: add `SdkCounter`

- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/SdkUpDownCounter.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/SdkUpDownCounterSuite.scala
|-|-|
| Spec | https://opentelemetry.io/docs/specs/otel/metrics/api/#updowncounter |
| Java implementation | [SdkLongUpDownCounter.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkLongUpDownCounter.java)  |
> sdk-metrics: add `SdkUpDownCounter`

- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/SdkHistogram.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/SdkHistogramSuite.scala
|-|-|
| Spec | https://opentelemetry.io/docs/specs/otel/metrics/api/#histogram |
| Java implementation | [SdkLongHistogram.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkLongHistogram.java)  |
> sdk-metrics: add `SdkHistogram`

- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/SdkObservableCounter.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/internal/MeterSharedState.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/SdkObservableCounterSuite.scala
|-|-|
| Spec | https://opentelemetry.io/docs/specs/otel/metrics/api/#asynchronous-counter |
| Java implementation | [SdkLongCounter.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkLongCounter.java) <br> [SdkObservableInstrument.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkObservableInstrument.java) |
> sdk-metrics: add `SdkObservableCounter`

- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/SdkObservableUpDownCounter.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/SdkObservableUpDownCounterSuite.scala
|-|-|
| Spec | https://opentelemetry.io/docs/specs/otel/metrics/api/#asynchronous-updowncounter |
| Java implementation | [SdkLongUpDownCounter.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkLongUpDownCounter.java) <br> [SdkObservableInstrument.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkObservableInstrument.java) |
> sdk-metrics: add `SdkObservableUpDownCounter`

- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/SdkObservableGauge.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/SdkObservableGaugeSuite.scala
|-|-|
| Spec | https://opentelemetry.io/docs/specs/otel/metrics/api/#asynchronous-gauge |
| Java implementation | [SdkLongGauge.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkLongGauge.java) <br> [SdkObservableInstrument.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkObservableInstrument.java) |
> sdk-metrics: add `SdkObservableGauge`

- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/exporter/ConsoleMetricExporter.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/exporter/ConsoleMetricExporterSuite.scala
|-|-|
| Java implementation | [LoggingMetricExporter.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/exporters/logging/src/main/java/io/opentelemetry/exporter/logging/LoggingMetricExporter.java) |
> sdk-metrics: add `ConsoleMetricExporter `

- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/SdkMeter.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/SdkMeterBuilder.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/SdkMeterProvider.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/view/RegisteredView.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/SdkMeterProviderSuite.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/exporter/InMemoryMetricReader.scala
|-|-|
| Spec | https://opentelemetry.io/docs/specs/otel/metrics/api/#meterprovider |
| Java implementation | [SdkMeterProvider.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkMeterProvider.java) |
> sdk-metrics: add `SdkMeterProvider` and `SdkMeterBuilder`

- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/autoconfigure/MetricExportersAutoConfigure.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/autoconfigure/MetricExportersAutoConfigureSuite.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/autoconfigure/SpanExportersAutoConfigure.scala
A built-in way to auto-configure metric exporters.
> sdk-metrics: add `MetricExportersAutoConfigure`

- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/SdkMeterProvider.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/autoconfigure/MeterProviderAutoConfigure.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/autoconfigure/MetricReadersAutoConfigure.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/exporter/MetricExporter.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/SdkMeterProviderSuite.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/autoconfigure/MeterProviderAutoConfigureSuite.scala
|-|-|
| Java implementation | [MeterProviderConfiguration.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/MeterProviderConfiguration.java) |
> sdk-metrics: add `MeterProviderAutoConfigure`

- .github/workflows/ci.yml
- build.sbt
- sdk/metrics-testkit/src/main/scala/org/typelevel/otel4s/sdk/testkit/metrics/InMemoryMetricExporter.scala
- sdk/metrics-testkit/src/main/scala/org/typelevel/otel4s/sdk/testkit/metrics/InMemoryMetricReader.scala
- sdk/metrics-testkit/src/main/scala/org/typelevel/otel4s/sdk/testkit/metrics/MetricsTestkit.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/SdkMeterProvider.scala
A drop-in replacement for the [oteljava MetricsTestkit](https://github.com/typelevel/otel4s/blob/main/oteljava/metrics-testkit/src/main/scala/org/typelevel/otel4s/oteljava/testkit/metrics/MetricsTestkit.scala).
> sdk-metrics-testkit: add `MetricsTestkit`

- build.sbt
- sdk-exporter/metrics/docker/config/otel-collector-config.yaml
- sdk-exporter/metrics/docker/config/prometheus.yaml
- sdk-exporter/metrics/docker/docker-compose.yml
- sdk-exporter/metrics/src/main/scala/org/typelevel/otel4s/sdk/exporter/otlp/metrics/OtlpHttpMetricExporter.scala
- sdk-exporter/metrics/src/test/scala/org/typelevel/otel4s/sdk/exporter/otlp/metrics/OtlpHttpMetricExporterSuite.scala
- sdk-exporter/trace/src/main/scala/org/typelevel/otel4s/sdk/exporter/otlp/trace/autoconfigure/OtlpSpanExporterAutoConfigure.scala
- sdk/metrics-testkit/src/main/scala/org/typelevel/otel4s/sdk/testkit/metrics/MetricsTestkit.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/data/PointData.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/data/PointDataSuite.scala
- sdk/testkit/src/main/scala/org/typelevel/otel4s/sdk/testkit/OpenTelemetrySdkTestkit.scala
|-|-|
| Java implementation | [OtlpHttpMetricExporter.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/http/metrics/OtlpHttpMetricExporter.java) <br> [OtlpHttpMetricExporterBuilder.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/http/metrics/OtlpHttpMetricExporterBuilder.java) <br>  |
> sdk-exporter-metrics: add `OtlpHttpMetricExporter`

- sdk-exporter/common/src/main/scala/org/typelevel/otel4s/sdk/exporter/otlp/Protocol.scala
- sdk-exporter/common/src/main/scala/org/typelevel/otel4s/sdk/exporter/otlp/autoconfigure/ProtocolAutoConfigure.scala
- sdk-exporter/common/src/test/scala/org/typelevel/otel4s/sdk/exporter/autoconfigure/ProtocolAutoConfigureSuite.scala
- sdk-exporter/trace/src/main/scala/org/typelevel/otel4s/sdk/exporter/otlp/trace/autoconfigure/OtlpSpanExporterAutoConfigure.scala
- sdk-exporter/trace/src/test/scala/org/typelevel/otel4s/sdk/exporter/otlp/trace/autoconfigure/OtlpSpanExporterAutoConfigureSuite.scala
Decoupling `Protocol` configuration to reuse it by the metrics exporter.
> sdk-exporter: add `ProtocolAutoConfigure`

- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/autoconfigure/SpanExportersAutoConfigure.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/autoconfigure/TracerProviderAutoConfigure.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/exporter/ConsoleSpanExporter.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/autoconfigure/SpanExportersAutoConfigureSuite.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/autoconfigure/TracerProviderAutoConfigureSuite.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/exporter/ConsoleSpanExporterSuite.scala
The `logging` exporter **name** has been deprecated since `v1.28.0 (2023-12-07)`. The actual [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.32.0/specification/configuration/sdk-environment-variables.md?plain=1#L251-L253):
> "logging" - It is a deprecated value left for backwards compatibility. It SHOULD
NOT be supported by new implementations.
The `sdk-metrics` module already uses a correct [name](https://github.com/typelevel/otel4s/blob/main/sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/exporter/ConsoleMetricExporter.scala).
Making the `sdk-trace` module up to date too.
> sdk-trace: rename `LoggingSpanExporter` to `ConsoleSpanExporter`

- build.sbt
- docs/sdk/overview.md
- examples/src/main/scala/SdkTracingExample.scala
- sdk-exporter/all/src/main/scala/org/typelevel/otel4s/sdk/exporter/otlp/autoconfigure/OtlpExportersAutoConfigure.scala
- sdk/all/src/main/scala/org/typelevel/otel4s/sdk/OpenTelemetrySdk.scala
- sdk/all/src/main/scala/org/typelevel/otel4s/sdk/autoconfigure/ExportersAutoConfigure.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/autoconfigure/MetricExportersAutoConfigure.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/autoconfigure/SpanExportersAutoConfigure.scala
A handy way to configure both exporters.
> sdk: add `ExportersAutoConfigure`

- build.sbt
- core/metrics/src/test/scala/org/typelevel/otel4s/metrics/BaseMeterSuite.scala
- oteljava/all/src/test/scala/org/typelevel/otel4s/oteljava/metrics/MeterSuite.scala
- oteljava/metrics-testkit/src/main/scala/org/typelevel/otel4s/oteljava/testkit/metrics/MetricsTestkit.scala
- oteljava/metrics/src/main/scala/org/typelevel/otel4s/oteljava/metrics/ContextUtils.scala
- oteljava/metrics/src/main/scala/org/typelevel/otel4s/oteljava/metrics/CounterBuilderImpl.scala
- oteljava/metrics/src/main/scala/org/typelevel/otel4s/oteljava/metrics/HistogramBuilderImpl.scala
- oteljava/metrics/src/main/scala/org/typelevel/otel4s/oteljava/metrics/MeterBuilderImpl.scala
- oteljava/metrics/src/main/scala/org/typelevel/otel4s/oteljava/metrics/MeterImpl.scala
- oteljava/metrics/src/main/scala/org/typelevel/otel4s/oteljava/metrics/Metrics.scala
- oteljava/metrics/src/main/scala/org/typelevel/otel4s/oteljava/metrics/UpDownCounterBuilderImpl.scala
- oteljava/testkit/src/main/scala/org/typelevel/otel4s/oteljava/testkit/OtelJavaTestkit.scala
- sdk/all/src/test/scala/org/typelevel/otel4s/sdk/metrics/SdkMeterSuite.scala
- sdk/metrics-testkit/src/main/scala/org/typelevel/otel4s/sdk/testkit/metrics/MetricsTestkit.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/SdkHistogramSuite.scala
- sdk/testkit/src/main/scala/org/typelevel/otel4s/sdk/testkit/OpenTelemetrySdkTestkit.scala
This PR accomplishes two things:
**1) fixes `oteljava` backend to capture exemplars correctly**
OpenTelemetry Java uses `JContext.current()` to attach trace_id/span_id to an exemplar. The context cannot be propagated seamlessly between CE IOLocal and oteljava ThreadLocal. There are more details: https://github.com/typelevel/otel4s/issues/202 and a possible fix https://github.com/typelevel/otel4s/pull/214 (waiting for CE, though).
To make it work, we can propagate the context manually. 
**2) tests both implementations (`sdk` and `oteljava`) using a shared `BaseMeterSuite`** 
That way we can guarantee that the behavior is identical
> oteljava: correctly capture exemplars. sdk, oteljava: use shared `BaseMeterSuite`

- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/SdkMeterProvider.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/aggregation/Aggregator.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/aggregation/ExplicitBucketHistogramAggregator.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/aggregation/SumAggregator.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/exemplar/ExemplarReservoir.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/exemplar/Reservoirs.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/internal/MeterSharedState.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/internal/storage/AsynchronousStorage.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/internal/storage/MetricStorage.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/internal/storage/SynchronousStorage.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/aggregation/AggregatorSuite.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/aggregation/ExplicitBucketHistogramAggregatorSuite.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/aggregation/SumAggregatorSuite.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/internal/MeterSharedStateSuite.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/internal/storage/SynchronousStorageSuite.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/test/InMemoryMeterSharedState.scala
Closes https://github.com/typelevel/otel4s/issues/664.
> sdk-metrics: use `ExemplarReservoirs` when they are really needed

- README.md
- docs/index.md
- docs/sdk/configuration.md
- docs/sdk/overview.md
Bringing some clarity regarding different backends and explaining metrics-specific SDK configuration options.
> docs: add SDK metrics-specific sections

- core/metrics/src/test/scala/org/typelevel/otel4s/metrics/BaseMeterSuite.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/SdkCounter.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/SdkHistogram.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/SdkUpDownCounter.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/aggregation/Aggregator.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/internal/Advice.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/internal/InstrumentDescriptor.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/scalacheck/Gens.scala
|-|-|
| Spec | https://opentelemetry.io/docs/specs/otel/metrics/api/#instrument-advisory-parameters |
| Java implementation | [Advice.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/descriptor/Advice.java)  |
> sdk-metrics: add `Advice`

- sdk/trace-testkit/src/main/scala/org/typelevel/otel4s/sdk/testkit/trace/TracesTestkit.scala
Unfortunately, the flaky tests don't fail locally. 
I have a gut feeling there may be something wrong with the cancelation of the pending export tasks. 
For instance, oteljava's testkit uses `SimpleSpanProcessor` too: https://github.com/typelevel/otel4s/blob/main/oteljava/trace-testkit/src/main/scala/org/typelevel/otel4s/oteljava/testkit/trace/TracesTestkit.scala#L94-L95.
> sdk: fix flaky `SdkTracerSuite` test

- build.sbt
- core/metrics/src/main/scala-2/org/typelevel/otel4s/metrics/GaugeMacro.scala
- core/metrics/src/main/scala-3/org/typelevel/otel4s/metrics/GaugeMacro.scala
- core/metrics/src/main/scala/org/typelevel/otel4s/metrics/Gauge.scala
- core/metrics/src/main/scala/org/typelevel/otel4s/metrics/Meter.scala
- core/metrics/src/test/scala/org/typelevel/otel4s/metrics/BaseMeterSuite.scala
- oteljava/metrics/src/main/scala/org/typelevel/otel4s/oteljava/metrics/GaugeBuilderImpl.scala
- oteljava/metrics/src/main/scala/org/typelevel/otel4s/oteljava/metrics/MeterImpl.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/Aggregation.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/InstrumentType.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/NoopInstrumentBuilder.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/SdkGauge.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/SdkMeter.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/aggregation/Aggregator.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/aggregation/LastValueAggregator.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/AggregationSuite.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/NoopInstrumentBuilderSuite.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/SdkMeterSuite.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/aggregation/AggregatorSuite.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/aggregation/LastValueAggregatorSuite.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/internal/MeterSharedStateSuite.scala
Synchronous gauge is stable since [1.33.0](https://github.com/open-telemetry/opentelemetry-specification/releases/tag/v1.33.0) - https://github.com/open-telemetry/opentelemetry-specification/pull/4019.
Related changes:
- https://github.com/open-telemetry/opentelemetry-java/pull/6419
~`oteljava` waits for the `1.38.0` release.~
The changeset:
> metrics: support synchronous gauge

- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/autoconfigure/ContextPropagatorsAutoConfigure.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/context/propagation/OtTracePropagator.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/autoconfigure/ContextPropagatorsAutoConfigureSuite.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/context/propagation/OtTracePropagatorSuite.scala
Resovles part of https://github.com/typelevel/otel4s/issues/616
Fully inspired by [JaegerPropagator ](https://github.com/typelevel/otel4s/blob/main/sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/context/propagation/JaegerPropagator.scala), [JaegerPropagatorSuite ](https://github.com/typelevel/otel4s/blob/main/sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/context/propagation/JaegerPropagatorSuite.scala) and [OtTracePropagator](https://github.com/open-telemetry/opentelemetry-java/blob/main/extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/OtTracePropagator.java)
> added OtTracePropagator

- build.sbt
- docs/sdk/configuration.md
- sdk/all/src/main/scala/org/typelevel/otel4s/sdk/OpenTelemetrySdk.scala
- sdk/all/src/test/scala/org/typelevel/otel4s/sdk/OpenTelemetrySdkSuite.scala
- sdk/common/js/src/main/scala/org/typelevel/otel4s/sdk/resource/HostDetectorPlatform.scala
- sdk/common/js/src/main/scala/org/typelevel/otel4s/sdk/resource/OS.scala
- sdk/common/jvm/src/main/scala/org/typelevel/otel4s/sdk/resource/HostDetectorPlatform.scala
- sdk/common/native/src/main/scala/org/typelevel/otel4s/sdk/resource/HostDetectorPlatform.scala
- sdk/common/shared/src/main/scala/org/typelevel/otel4s/sdk/autoconfigure/TelemetryResourceAutoConfigure.scala
- sdk/common/shared/src/main/scala/org/typelevel/otel4s/sdk/resource/HostDetector.scala
- sdk/common/shared/src/main/scala/org/typelevel/otel4s/sdk/resource/TelemetryResourceDetector.scala
- sdk/common/shared/src/test/scala/org/typelevel/otel4s/sdk/autoconfigure/TelemetryResourceAutoConfigureSuite.scala
- sdk/common/shared/src/test/scala/org/typelevel/otel4s/sdk/resource/TelemetryResourceDetectorSuite.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/SdkMetrics.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/SdkMetricsSuite.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/SdkTraces.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/SdkTracesSuite.scala
- semconv/stable/src/main/scala/org/typelevel/otel4s/semconv/SchemaUrls.scala
- semconv/stable/src/test/scala/org/typelevel/otel4s/semconv/SchemaUrlsSuite.scala
|-|-|
| Spec | https://opentelemetry.io/docs/specs/semconv/resource/host/ |
| Java implementation | [HostResource.java](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/resources/library/src/main/java/io/opentelemetry/instrumentation/resources/HostResource.java) |
| JavaScript implementation | [HostDetectorSync.ts](https://github.com/open-telemetry/opentelemetry-js/blob/v1.25.1/packages/opentelemetry-resources/src/detectors/platform/node/HostDetectorSync.ts) |
We need `TelemetryResourceDetector` to build environment-aware `TelemetryResource` for our Scala SDK.
Some context: https://github.com/typelevel/otel4s/issues/615.
> sdk-common: add `TelemetryResourceDetector`

- docs/sdk/configuration.md
- sdk/all/src/main/scala/org/typelevel/otel4s/sdk/OpenTelemetrySdk.scala
- sdk/common/js/src/main/scala/org/typelevel/otel4s/sdk/resource/OSDetectorPlatform.scala
- sdk/common/jvm-native/src/main/scala/org/typelevel/otel4s/sdk/resource/OSDetectorPlatform.scala
- sdk/common/shared/src/main/scala/org/typelevel/otel4s/sdk/autoconfigure/TelemetryResourceAutoConfigure.scala
- sdk/common/shared/src/main/scala/org/typelevel/otel4s/sdk/resource/OSDetector.scala
- sdk/common/shared/src/main/scala/org/typelevel/otel4s/sdk/resource/TelemetryResourceDetector.scala
- sdk/common/shared/src/test/scala/org/typelevel/otel4s/sdk/autoconfigure/TelemetryResourceAutoConfigureSuite.scala
- sdk/common/shared/src/test/scala/org/typelevel/otel4s/sdk/resource/TelemetryResourceDetectorSuite.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/SdkMetrics.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/SdkTraces.scala
|-|-|
| Spec | https://opentelemetry.io/docs/specs/semconv/resource/os/ |
| Java implementation | [OsResource.java](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/resources/library/src/main/java/io/opentelemetry/instrumentation/resources/OsResource.java) |
| JavaScript implementation | [OSDetectorSync.ts](https://github.com/open-telemetry/opentelemetry-js/blob/v1.25.1/packages/opentelemetry-resources/src/detectors/platform/node/OSDetectorSync.ts) |
> sdk-common: add `OSDetector`

- docs/sdk/configuration.md
- sdk/all/src/main/scala/org/typelevel/otel4s/sdk/OpenTelemetrySdk.scala
- sdk/common/js/src/main/scala/org/typelevel/otel4s/sdk/resource/Process.scala
- sdk/common/js/src/main/scala/org/typelevel/otel4s/sdk/resource/ProcessRuntimeDetectorPlatform.scala
- sdk/common/jvm/src/main/scala/org/typelevel/otel4s/sdk/resource/ProcessRuntimeDetectorPlatform.scala
- sdk/common/native/src/main/scala/org/typelevel/otel4s/sdk/resource/ProcessRuntimeDetectorPlatform.scala
- sdk/common/shared/src/main/scala/org/typelevel/otel4s/sdk/autoconfigure/TelemetryResourceAutoConfigure.scala
- sdk/common/shared/src/main/scala/org/typelevel/otel4s/sdk/resource/ProcessRuntimeDetector.scala
- sdk/common/shared/src/main/scala/org/typelevel/otel4s/sdk/resource/TelemetryResourceDetector.scala
- sdk/common/shared/src/test/scala/org/typelevel/otel4s/sdk/autoconfigure/TelemetryResourceAutoConfigureSuite.scala
- sdk/common/shared/src/test/scala/org/typelevel/otel4s/sdk/resource/TelemetryResourceDetectorSuite.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/SdkMetrics.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/SdkTraces.scala
|-|-|
| Spec | https://opentelemetry.io/docs/specs/semconv/resource/process/#process-runtimes |
| Java implementation | [ProcessRuntimeResource.java](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/resources/library/src/main/java/io/opentelemetry/instrumentation/resources/ProcessRuntimeResource.java) |
| JavaScript implementation | [ProcessDetectorSync.ts](https://github.com/open-telemetry/opentelemetry-js/blob/v1.25.1/packages/opentelemetry-resources/src/detectors/platform/node/ProcessDetectorSync.ts) |
> sdk-common: add `ProcessRuntimeDetector`

- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/SdkCounter.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/SdkGauge.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/SdkHistogram.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/SdkUpDownCounter.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/SdkSpanBackend.scala
`{instrument}.meta` is always used by the macro under the hood: `Counter#add`, `Histogram#record`, etc. So, it makes sense to allocate it only once. 
Instruments in the `oteljava` module also define `meta` as a const variable.
> sdk-trace: define `meta: InstrumentMeta[F]` as `val`

- core/metrics/src/main/scala/org/typelevel/otel4s/metrics/Counter.scala
- core/metrics/src/main/scala/org/typelevel/otel4s/metrics/UpDownCounter.scala
- core/metrics/src/test/scala/org/typelevel/otel4s/metrics/CounterSuite.scala
- core/metrics/src/test/scala/org/typelevel/otel4s/metrics/HistogramSuite.scala
- core/metrics/src/test/scala/org/typelevel/otel4s/metrics/UpDownCounterSuite.scala
> core-metrics: remove typed backend such as `{X}.LongBackend`, `{X}.DoubleBackend`

- core/metrics/src/main/scala-2/org/typelevel/otel4s/metrics/HistogramMacro.scala
- core/metrics/src/main/scala-3/org/typelevel/otel4s/metrics/HistogramMacro.scala
- core/metrics/src/main/scala/org/typelevel/otel4s/metrics/Histogram.scala
- core/metrics/src/test/scala/org/typelevel/otel4s/metrics/HistogramSuite.scala
- oteljava/metrics/src/main/scala/org/typelevel/otel4s/oteljava/metrics/HistogramBuilderImpl.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/SdkHistogram.scala
I cannot recall why it was implemented that way in the very first place. 
`Histogram.Meta` was needed to provide the `def resourceUnit: Resource[F, Unit]`. However, we can construct `Resource.unit` anywhere since it doesn't require `Applicative`.
> core-metrics: remove `Histogram.Meta` in favor of `InstrumentMeta`

- docs/customization/histogram-custom-buckets/README.md
- docs/examples/grafana/README.md
- docs/examples/honeycomb/README.md
- docs/examples/jaeger-docker/README.md
- docs/index.md
- docs/instrumentation/metrics.md
- docs/instrumentation/tracing.md
- sdk-exporter/common/src/main/scala/org/typelevel/otel4s/sdk/exporter/otlp/autoconfigure/OtlpHttpClientAutoConfigure.scala
- sdk/all/src/main/scala/org/typelevel/otel4s/sdk/OpenTelemetrySdk.scala
- sdk/common/shared/src/main/scala/org/typelevel/otel4s/sdk/autoconfigure/TelemetryResourceAutoConfigure.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/autoconfigure/ExemplarFilterAutoConfigure.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/autoconfigure/MetricExportersAutoConfigure.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/autoconfigure/BatchSpanProcessorAutoConfigure.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/autoconfigure/ContextPropagatorsAutoConfigure.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/autoconfigure/SamplerAutoConfigure.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/autoconfigure/SpanExportersAutoConfigure.scala
> docs: update OpenTelemetry configuration links

- oteljava/common/src/main/scala/org/typelevel/otel4s/oteljava/context/propagation/JavaPropagatorWrappers.scala
- oteljava/common/src/test/scala/org/typelevel/otel4s/oteljava/context/propagation/PropagatorConvertersSuite.scala
Before this change, the `toString` didn't provide any useful information:
```scala
OtelJava.autoConfigured[IO]().use { otel4s =>
IO.println("Propagators: " + otel4s.propagators)
}
```
Prints:
```
Propagators: ContextPropagators.Default{textMapPropagator=
org.typelevel.otel4s.oteljava.context.propagation.JavaPropagatorWrappers$JTextMapPropagatorWrapper@47a8424c}
```
> oteljava: TextMapPropagatorWrapper - add meaningful `toString`

- build.sbt
This should prevent useless PRs like:
* #746 
* #716 
* #689
https://github.com/scala-steward-org/scala-steward/blob/806529ada57067262eaf9425efe52bb2249b6047/docs/repo-specific-configuration.md?plain=1#L210
> Let Scala Steward ignore otel4s-java updates

- build.sbt
- sdk/common/shared/src/test/scala/org/typelevel/otel4s/sdk/resource/TelemetryResourceDetectorSuite.scala
That way we can be sure we are using correct attributes.
> sdk-common: use `semconv-experimental` in tests

- build.sbt
- core/metrics/src/main/scala/org/typelevel/otel4s/metrics/Histogram.scala
> core-trace: remove `Histogram.DoubleBackend`

- core/metrics/src/main/scala-2/org/typelevel/otel4s/metrics/HistogramMacro.scala
- core/metrics/src/main/scala-3/org/typelevel/otel4s/metrics/HistogramMacro.scala
- core/metrics/src/main/scala/org/typelevel/otel4s/metrics/Histogram.scala
- core/metrics/src/test/scala/org/typelevel/otel4s/metrics/HistogramSuite.scala
- oteljava/metrics/src/main/scala/org/typelevel/otel4s/oteljava/metrics/HistogramBuilderImpl.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/SdkHistogram.scala
There is also a major behavior change: `recordDuration` no longer adds `cause` attribute by default.
To preserve old behavior, users must use `histogram.recordDuration(TimeUnit.SECONDS, Histogram.recordCause)`.
`cause` attribute is opinionated and doesn't go along with most of the semantic conventions. 
In most conventions, it would be [error.type](https://opentelemetry.io/docs/specs/semconv/database/database-metrics/#metric-dbclientoperationduration) instead.
> core-trace: use `ExitCase` to build attributes in `Histogram#recordDuration`

- build.sbt
- buildscripts/semantic-convention/templates/registry/otel4s/metrics/SemanticMetrics.scala.j2
- semconv/metrics/experimental/src/main/scala/org/typelevel/otel4s/semconv/experimental/metrics/ContainerExperimentalMetrics.scala
- semconv/metrics/experimental/src/main/scala/org/typelevel/otel4s/semconv/experimental/metrics/DbExperimentalMetrics.scala
- semconv/metrics/experimental/src/main/scala/org/typelevel/otel4s/semconv/experimental/metrics/DnsExperimentalMetrics.scala
- semconv/metrics/experimental/src/main/scala/org/typelevel/otel4s/semconv/experimental/metrics/FaasExperimentalMetrics.scala
- semconv/metrics/experimental/src/main/scala/org/typelevel/otel4s/semconv/experimental/metrics/GenAiExperimentalMetrics.scala
- semconv/metrics/experimental/src/main/scala/org/typelevel/otel4s/semconv/experimental/metrics/HttpExperimentalMetrics.scala
- semconv/metrics/experimental/src/main/scala/org/typelevel/otel4s/semconv/experimental/metrics/JvmExperimentalMetrics.scala
- semconv/metrics/experimental/src/main/scala/org/typelevel/otel4s/semconv/experimental/metrics/MessagingExperimentalMetrics.scala
- semconv/metrics/experimental/src/main/scala/org/typelevel/otel4s/semconv/experimental/metrics/ProcessExperimentalMetrics.scala
- semconv/metrics/experimental/src/main/scala/org/typelevel/otel4s/semconv/experimental/metrics/SystemExperimentalMetrics.scala
- semconv/metrics/stable/src/main/scala/org/typelevel/otel4s/semconv/metrics/HttpMetrics.scala
- semconv/metrics/stable/src/main/scala/org/typelevel/otel4s/semconv/metrics/JvmMetrics.scala
A minor improvement. That way we can also ensure that we use valid attributes.
> semconv-metrics: use a reference to semantic attributes

- sdk/all/src/main/scala/org/typelevel/otel4s/sdk/OpenTelemetrySdk.scala
- sdk/all/src/test/scala/org/typelevel/otel4s/sdk/OpenTelemetrySdkSuite.scala
- sdk/all/src/test/scala/org/typelevel/otel4s/sdk/trace/SdkTracerSuite.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/SdkSpanBuilder.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/SdkTracerProvider.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/SdkTraces.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/TracerSharedState.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/autoconfigure/SamplerAutoConfigure.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/autoconfigure/TracerProviderAutoConfigure.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/samplers/ParentBasedSampler.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/samplers/Sampler.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/samplers/TraceIdRatioBasedSampler.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/SdkSpanBuilderSuite.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/SdkTracesSuite.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/autoconfigure/SamplerAutoConfigureSuite.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/autoconfigure/TracerProviderAutoConfigureSuite.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/samplers/ParentBasedSamplerSuite.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/samplers/SamplerSuite.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/samplers/TraceIdRatioBasedSamplerSuite.scala
Sampler, unfortunately, can be effectful. 
For example: https://github.com/open-telemetry/opentelemetry-java-contrib/blob/main/aws-xray/src/main/java/io/opentelemetry/contrib/awsxray/AwsXrayRemoteSampler.java.
> sdk-trace: make `Sampler` effectful

- core/common/src/main/scala/org/typelevel/otel4s/AttributeKey.scala
- sdk-contrib/aws/resource/src/main/scala/org/typelevel/otel4s/sdk/contrib/aws/resource/AwsBeanstalkDetector.scala
- sdk-contrib/aws/resource/src/main/scala/org/typelevel/otel4s/sdk/contrib/aws/resource/AwsEcsDetector.scala
- sdk-contrib/aws/resource/src/main/scala/org/typelevel/otel4s/sdk/contrib/aws/resource/AwsLambdaDetector.scala
- sdk/common/jvm-native/src/main/scala/org/typelevel/otel4s/sdk/resource/OSDetectorPlatform.scala
- sdk/common/jvm/src/main/scala/org/typelevel/otel4s/sdk/resource/HostDetectorPlatform.scala
- sdk/common/jvm/src/main/scala/org/typelevel/otel4s/sdk/resource/ProcessDetectorPlatform.scala
- sdk/common/jvm/src/main/scala/org/typelevel/otel4s/sdk/resource/ProcessRuntimeDetectorPlatform.scala
- sdk/common/native/src/main/scala/org/typelevel/otel4s/sdk/resource/HostDetectorPlatform.scala
Resolves #2 (in some way). 
Adding optional attribute values is rather verbose. To make these operations more bearable, we can allow passing optional values.
> core-common: `AttributeKey` add `maybe` method

- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/autoconfigure/BatchSpanProcessorAutoConfigure.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/processor/BatchSpanProcessor.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/processor/SimpleSpanProcessor.scala
They are still accessible via `apply` or `builder`, but the target type is `SpanProcessor` instead.
> sdk-trace: make `SimpleSpanProcessor` and `BatchSpanProcessor` private

- benchmarks/src/main/scala/org/typelevel/otel4s/benchmarks/BatchSpanProcessorBenchmark.scala
- build.sbt
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/processor/BatchSpanProcessor.scala
First step towards #786. The idea of the benchmark is partially based on the [BatchSpanProcessorBenchmark.java](https://github.com/open-telemetry/opentelemetry-java/blob/697b4e0c7021eeff545afa7b2929ad8ab2bd3474/sdk/trace/src/jmh/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorBenchmark.java#L29) with some adjustments. 
`delayMs` represents how long it takes for the exporter to export spans. Besides `LoggingExporter`, the export of spans will take at least 5+ ms.
So, SDK outperforms OtelJava in this case:
```
throughput                           oteljava                     sdk                        diff   
doExport delayMs=0 spanCount=1000    8819.323 ± 3730.817 ops/s    2233.270 ± 63.993 ops/s    6586.05
doExport delayMs=0 spanCount=2000    3797.170 ± 1309.373 ops/s    1188.510 …
```
> benchmarks: add `BatchSpanProcessor` benchmark

- benchmarks/src/main/scala/org/typelevel/otel4s/benchmarks/TraceBenchmark.scala
- build.sbt
- sdk/all/src/test/scala/org/typelevel/otel4s/sdk/OpenTelemetrySdkSuite.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/SdkSpanBackend.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/SdkSpanBuilder.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/SdkTracer.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/SdkTracerBuilder.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/SdkTracerProvider.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/SpanStorage.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/TracerSharedState.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/SdkSpanBackendSuite.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/SdkSpanBuilderSuite.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/SdkTracesSuite.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/autoconfigure/TracerProviderAutoConfigureSuite.scala
Before:
```
Benchmark                               (backend)   Mode  Cnt      Score      Error   Units
TraceBenchmark.span                           sdk  thrpt   80  37936.668 ± 1867.799   ops/s
TraceBenchmark.span:async                     sdk  thrpt             NaN                ---
TraceBenchmark.span:gc.alloc.rate             sdk  thrpt   80   1721.229 ±   62.352  MB/sec
TraceBenchmark.span:gc.alloc.rate.norm        sdk  thrpt   80  48424.089 ± 2845.034    B/op
TraceBenchmark.span:gc.count                  sdk  thrpt   80     93.000             counts
TraceBenchmark.span:gc.time                   sdk  thrpt   80   5132.000                 ms
```
After:
```
Benchmark                               (backend)   Mode  Cnt      Score      Error   Units
TraceBenchmark.span …
```
> sdk-trace: use `MapRef` in `SpanStorage`

- build.sbt
Use the scalac version for testing the scalfix rules that matches the one from scalafix.
Finishes #755
Apply fix from: https://github.com/typelevel/sbt-tpolecat/pull/238
> Sync the scalac version with the one used by scalafix

- sdk-exporter/prometheus/src/main/scala/org/typelevel/otel4s/sdk/exporter/prometheus/PrometheusMetricExporter.scala
- sdk-exporter/prometheus/src/main/scala/org/typelevel/otel4s/sdk/exporter/prometheus/PrometheusWriter.scala
- sdk-exporter/prometheus/src/main/scala/org/typelevel/otel4s/sdk/exporter/prometheus/autoconfigure/PrometheusMetricExporterAutoConfigure.scala
- sdk-exporter/prometheus/src/test/scala/org/typelevel/otel4s/sdk/exporter/prometheus/PrometheusWriterSuite.scala
- sdk-exporter/prometheus/src/test/scala/org/typelevel/otel4s/sdk/exporter/prometheus/autoconfigure/PrometheusMetricExporterAutoConfigureSuite.scala
A bit of unification of the config properties:
- noUnits -> unitSuffixDisabled
- noTypeSuffixes -> typeSuffixDisabled
- disabledScopeInfo -> scopeInfoDisabled
- disabledTargetInfo -> targetInfoDisabled
> sdk-exporter-prometheus: unify `PrometheusWriter.Config` options

- buildscripts/semantic-convention/templates/registry/otel4s/metrics/SemanticMetrics.scala.j2
- semconv/metrics/experimental/src/main/scala/org/typelevel/otel4s/semconv/experimental/metrics/ContainerExperimentalMetrics.scala
- semconv/metrics/experimental/src/main/scala/org/typelevel/otel4s/semconv/experimental/metrics/DbExperimentalMetrics.scala
- semconv/metrics/experimental/src/main/scala/org/typelevel/otel4s/semconv/experimental/metrics/DnsExperimentalMetrics.scala
- semconv/metrics/experimental/src/main/scala/org/typelevel/otel4s/semconv/experimental/metrics/FaasExperimentalMetrics.scala
- semconv/metrics/experimental/src/main/scala/org/typelevel/otel4s/semconv/experimental/metrics/GenAiExperimentalMetrics.scala
- semconv/metrics/experimental/src/main/scala/org/typelevel/otel4s/semconv/experimental/metrics/HttpExperimentalMetrics.scala
- semconv/metrics/experimental/src/main/scala/org/typelevel/otel4s/semconv/experimental/metrics/HwExperimentalMetrics.scala
- semconv/metrics/experimental/src/main/scala/org/typelevel/otel4s/semconv/experimental/metrics/JvmExperimentalMetrics.scala
- semconv/metrics/experimental/src/main/scala/org/typelevel/otel4s/semconv/experimental/metrics/K8sExperimentalMetrics.scala
- semconv/metrics/experimental/src/main/scala/org/typelevel/otel4s/semconv/experimental/metrics/MessagingExperimentalMetrics.scala
- semconv/metrics/experimental/src/main/scala/org/typelevel/otel4s/semconv/experimental/metrics/NodejsExperimentalMetrics.scala
- semconv/metrics/experimental/src/main/scala/org/typelevel/otel4s/semconv/experimental/metrics/ProcessExperimentalMetrics.scala
- semconv/metrics/experimental/src/main/scala/org/typelevel/otel4s/semconv/experimental/metrics/RpcExperimentalMetrics.scala
- semconv/metrics/experimental/src/main/scala/org/typelevel/otel4s/semconv/experimental/metrics/SystemExperimentalMetrics.scala
- semconv/metrics/experimental/src/main/scala/org/typelevel/otel4s/semconv/experimental/metrics/V8jsExperimentalMetrics.scala
- semconv/metrics/stable/src/main/scala/org/typelevel/otel4s/semconv/metrics/HttpMetrics.scala
- semconv/metrics/stable/src/main/scala/org/typelevel/otel4s/semconv/metrics/JvmMetrics.scala
It's an oversight from the original implementation: we shouldn't decide for a user which type of instrument they will use.
Bonus point: `createObserver` and `createWithCallback`.
> semconv-metrics: do not force a type of instrument

- sdk/common/shared/src/main/scala/org/typelevel/otel4s/sdk/internal/ComponentRegistry.scala
- sdk/common/shared/src/test/scala/org/typelevel/otel4s/sdk/internal/ComponentRegistrySuite.scala
A new specification update has been released: https://github.com/open-telemetry/opentelemetry-specification/releases/tag/v1.38.0.
`Attributes` are part of the instrument's identity now: https://github.com/open-telemetry/opentelemetry-specification/pull/4161.
> sdk-common: `ComponentRegistry` - use `attributes` as a part of identity

- core/trace/src/main/scala-2/org/typelevel/otel4s/trace/SpanBuilderMacro.scala
- core/trace/src/main/scala-2/org/typelevel/otel4s/trace/SpanMacro.scala
- core/trace/src/main/scala-2/org/typelevel/otel4s/trace/TracerMacro.scala
- core/trace/src/main/scala-3/org/typelevel/otel4s/trace/SpanBuilderMacro.scala
- core/trace/src/main/scala-3/org/typelevel/otel4s/trace/SpanMacro.scala
- core/trace/src/test/scala/org/typelevel/otel4s/trace/SpanBuilderSuite.scala
- core/trace/src/test/scala/org/typelevel/otel4s/trace/SpanSuite.scala
- core/trace/src/test/scala/org/typelevel/otel4s/trace/TracerSuite.scala
> core-trace: skip `addAttributes` when varargs are empty

- sdk-exporter/prometheus/src/main/scala/org/typelevel/otel4s/sdk/exporter/prometheus/PrometheusHttpRoutes.scala
- sdk-exporter/prometheus/src/test/scala/org/typelevel/otel4s/sdk/exporter/prometheus/PrometheusHttpRoutesSuite.scala
currently `curl -v -H "Accept:text/plain" http://localhost:9464/metrics` return 406. Fixed by reversing the logic of checking MediaRange.
> prometheus exporter: accept more text media type

- benchmarks/src/main/scala/org/typelevel/otel4s/benchmarks/MetricsBenchmark.scala
- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/internal/storage/SynchronousStorage.scala
Yet another part of the #786.
Measurment: average time, lower is better.
SDK is roughly 15% to 30% slower than the OtelJava.
```
Benchmark                      (backend)       (operation)     (variation)  Mode  Cnt      Score      Error   Units
eightThreadsCommonLabelSet      oteljava      long_counter            noop  avgt   10  28638.180 ±  3617.497   ns/op
eightThreadsCommonLabelSet      oteljava      long_counter  sdk_cumulative  avgt   10  27742.687 ±  1200.754   ns/op
eightThreadsCommonLabelSet      oteljava      long_counter       sdk_delta  avgt   10  28586.511 ±  2407.448   ns/op
eightThreadsCommonLabelSet           sdk      long_counter            noop  avgt   10  26353.959 ±   771.915   ns/op
eightThreadsCommonLabelSet           sdk      long_counter  sdk_cumulative  avgt   10 …
```
> benchmarks: add metrics benchmark

- build.sbt
- docs/sdk/configuration.md
- sdk-exporter/prometheus/src/main/scala/org/typelevel/otel4s/sdk/exporter/prometheus/PrometheusMetricExporter.scala
- sdk-exporter/prometheus/src/main/scala/org/typelevel/otel4s/sdk/exporter/prometheus/autoconfigure/PrometheusMetricExporterAutoConfigure.scala
- sdk-exporter/prometheus/src/test/scala/org/typelevel/otel4s/sdk/exporter/prometheus/autoconfigure/PrometheusMetricExporterAutoConfigureSuite.scala
Allow users to customize the shutdown timeout of exporter server. Default value is 10 seconds
> prometheus exporter: add shutdown timeout config

- sdk-exporter/prometheus/src/main/scala/org/typelevel/otel4s/sdk/exporter/prometheus/PrometheusHttpRoutes.scala
- sdk-exporter/prometheus/src/test/scala/org/typelevel/otel4s/sdk/exporter/prometheus/PrometheusHttpRoutesSuite.scala
It turns out that now Prometheus exporter endpoint returns `Not Acceptable` error response for GET request with `*/*` Accept header, while the more correct approach looks to treat it the same as non-existent Accept header, that is "user agent will accept any media type in response".
> Prometheus exporter: correctly treat wildcard Accept

- benchmarks/src/main/scala/org/typelevel/otel4s/benchmarks/MultiSpanProcessorBenchmark.scala
- build.sbt
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/SdkSpanBuilder.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/SdkTracerProvider.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/processor/BatchSpanProcessor.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/processor/SimpleSpanProcessor.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/processor/SpanProcessor.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/SdkSpanBackendSuite.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/processor/SpanProcessorSuite.scala
The original implementation of `SpanProcessor` is highly influenced by OpenTelemetry Java internals. 
For example, `isStartRequired` and `isEndRequired` are used for optimization purposes and also aren't required by the spec. 
We can replace:
```scala
def onStart(parentContext: Option[SpanContext], span: SpanRef[F]): F[Unit]
```
with:
```scala
def onStart: SpanProcessor.OnStart[F]
trait OnStart[F[_]] {
def apply(parentContext: Option[SpanContext], span: SpanRef[F]): F[Unit]
}
```
A noop implementation of `OnStart` can be filtered out when combining multiple processors.
> sdk: refactor SpanProcessor

- docs/oteljava/tracing-java-interop.md
- docs/tracing-context-propagation.md
- examples/src/main/scala/KleisliExample.scala
- examples/src/main/scala/PekkoHttpExample.scala
- oteljava/all/src/main/scala/org/typelevel/otel4s/oteljava/OtelJava.scala
- oteljava/all/src/test/scala/org/typelevel/otel4s/oteljava/OtelJavaSuite.scala
- oteljava/metrics/src/main/scala/org/typelevel/otel4s/oteljava/metrics/Metrics.scala
- oteljava/trace/src/main/scala/org/typelevel/otel4s/oteljava/trace/Traces.scala
We are slowly getting closer to `1.0` and I want to revisit the OtelJava API.
Currently, the situation is the following.
```scala
object OtelJava {
def forAsync[F[_]: Async: LocalContextProvider](jOtel: JOpenTelemetry): F[OtelJava[F]]
def local[F[_]: Async: LocalContext](jOtel: JOpenTelemetry): OtelJava[F]
def resource[F[_]: Async: LocalContextProvider](acquire: F[JOpenTelemetrySdk]): Resource[F, OtelJava[F]]
def autoConfigured[F[_]: Async: LocalContextProvider](customize: ...): Resource[F, OtelJava[F]]
def global[F[_]: Async: LocalContextProvider]: F[OtelJava[F]]
def noop[F[_]: Applicative: LocalContextProvider]: F[OtelJava[F]]
}
```
I'm confident in the following:
- `autoConfigured`
- `global`
- `resource`
- `noop`
And less confident in:
- `forAsync`
- `local`
Both are relatively …
> oteljava: refactor Metrics, Traces, and OtelJava API

- core/all/src/main/scala/org/typelevel/otel4s/Otel4s.scala
Add `implicit def localContext: Local[F, Ctx]` to `Otel4s`, where previously it was only defined on subtypes.
I think the reason we didn't do this originally is because we thought that in conflicted with no-op implementations—because `Local` has an API contract to adhere to which does not permit no-op implementations—but in practice all the `Otel4s` implementations define it anyway, and just have a working `Local` context in their no-op implementations
> Add implicit `Otel4s#localContext`

- core/common/src/main/scala/org/typelevel/otel4s/Attribute.scala
- oteljava/common/src/main/scala/org/typelevel/otel4s/oteljava/AttributeConverters.scala
That's the last public `case class` in the `core-*`. 
When it's a sealed trait, it should be easier to do binary-compatible changes to the `Attribute`.
> core-common: redefine `Attribute` as a sealed trait

- build.sbt
- core/all/src/main/scala/org/typelevel/otel4s/Otel4s.scala
- core/common/src/main/scala/org/typelevel/otel4s/baggage/Baggage.scala
- core/common/src/main/scala/org/typelevel/otel4s/baggage/BaggageManager.scala
- core/common/src/test/scala/org/typelevel/otel4s/baggage/BaggageManagerSuite.scala
- oteljava/all/src/main/scala/org/typelevel/otel4s/oteljava/OtelJava.scala
- oteljava/common/src/main/scala/org/typelevel/otel4s/oteljava/AttributeConverters.scala
- oteljava/common/src/main/scala/org/typelevel/otel4s/oteljava/baggage/BaggageConverters.scala
- oteljava/common/src/main/scala/org/typelevel/otel4s/oteljava/baggage/BaggageManagerImpl.scala
- oteljava/common/src/test/scala/org/typelevel/otel4s/oteljava/baggage/BaggageConvertersSuite.scala
- oteljava/common/src/test/scala/org/typelevel/otel4s/oteljava/baggage/BaggageManagerImplSuite.scala
- oteljava/testkit/src/main/scala/org/typelevel/otel4s/oteljava/testkit/OtelJavaTestkit.scala
- sdk/all/src/main/scala/org/typelevel/otel4s/sdk/OpenTelemetrySdk.scala
- sdk/common/shared/src/main/scala/org/typelevel/otel4s/sdk/baggage/SdkBaggageManager.scala
- sdk/common/shared/src/test/scala/org/typelevel/otel4s/sdk/baggage/SdkBaggageManagerSuite.scala
- sdk/testkit/src/main/scala/org/typelevel/otel4s/sdk/testkit/OpenTelemetrySdkTestkit.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/SdkContextKeys.scala
Add `BaggageManager` utility for accessing and modifying `Baggage` in `Local` context.
Closes #896.
I know that there are law tests for `Local`, but I couldn't figure them out in a reasonable amount of time and I have a $work project to focus on as well. Happy for someone else to add them if desired.
I believe all these changes are backwards binary compatible with the exception of `Otel4s` (which gets a new abstract method to implement), but you shouldn't be implementing your own `Otel4s` anyway
> Add `BaggageManager` utility

- core/common/src/main/scala/org/typelevel/otel4s/Attribute.scala
- core/common/src/main/scala/org/typelevel/otel4s/AttributeKey.scala
- core/common/src/test/scala/org/typelevel/otel4s/AttributeSuite.scala
Users would like to use a newtype/opaque types as an attribute. Currently, the API is cumbersome:
```scala
case class UserId(id: Int)
val id = UserId(1)
span.addAttribute(Attribute("id", id.value.toLong))
```
But we can make it more usable via `Attribute.From`:
```scala
case class UserId(id: Int)
implicit val userIdFrom: Attribute.From[UserId, Long] = _.id.toLong
val id = UserId(1)
span.addAttribute(Attribute.from("id", id))
```
According to the [specification](https://opentelemetry.io/docs/specs/otel/common/#attribute) the attribute value must always be one of: string, boolean, double, long, and array variants. 
So, we can't have the `Attribute[UserId]`.
_____
From the implementation standpoint, the definition is detached from the materialization. 
There are 4 components:
- …
> core-common: add `Attribute.from`

- core/common/src/main/scala/org/typelevel/otel4s/Attribute.scala
- core/common/src/test/scala/org/typelevel/otel4s/AttributeSuite.scala
Many codebases utilize newtype/opaque types for type safety. When converted to attributes, some entities must always use the same name. 
With `Attribute.Make` the conversion process can be simplified. 
____
The model definition:
```scala
case class UserId(id: Int)
object UserId {
implicit val userIdAttributeFrom: Attribute.From[UserId, Long] =
_.id.toLong
implicit val userIdAttributeMake: Attribute.Make[UserId, Long] =
Attribute.Make.const("user.id")
}
```
```scala
def findUser(userId: UserId): F[Unit] = 
Tracer[F].span("findUser", Attribute("user.id", userId.id.toLong))
```
```scala
def findUser(userId: UserId): F[Unit] = 
Tracer[F].span("findUser", Attribute.from(userId))
```
> core-common: add `Attribute.Make`

- oteljava/context-storage/src/main/scala/org/typelevel/otel4s/oteljava/context/IOLocalContextStorage.scala
- oteljava/context-storage/src/main/scala/org/typelevel/otel4s/oteljava/context/IOLocalContextStorageProvider.scala
Eventually, we will instrument `getAgentLocalContext` by the OTeL Agent. 
That's how it is supposed to work: https://github.com/iRevive/opentelemetry-java-instrumentation/blob/b2f6501ec980194d0cb56f36d6bcc83c1d1b3b0b/instrumentation/otel4s/otel4s-0.12/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/otel4s/v0_12/IoLocalContextStorageInstrumentation.java#L27-L42.
> oteljava-context-storage: update agent instrumentation direction

- benchmarks/src/main/scala/org/typelevel/otel4s/benchmarks/SpanBuilderBenchmark.scala
- build.sbt
- oteljava/trace/src/main/scala/org/typelevel/otel4s/oteljava/trace/SpanBuilderImpl.scala
- oteljava/trace/src/main/scala/org/typelevel/otel4s/oteljava/trace/TracerImpl.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/SdkSpanBuilder.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/SdkTracer.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/SdkTracerProvider.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/TracerSharedState.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/SdkSpanBuilderSuite.scala
Some changes decoupled from https://github.com/typelevel/otel4s/pull/963. 
The changes:
- chain functions
- reuse `InstrumentMeta` instance
- add benchmark
`addParamsAndUse` is the most relevant benchmark. The throughput is roughly the same, and the normalized memory usage is slightly lower. But realistically, there is no difference. 
```
Benchmark                             (backend)  Mode  Cnt      Score      Error   Units
addParams                                  noop  avgt   80      1.177 ±    0.010   ns/op
addParams:gc.alloc.rate.norm               noop  avgt   80     ≈ 10⁻³               B/op
addParams                              oteljava  avgt   80     61.681 ±    0.221   ns/op
addParams:gc.alloc.rate.norm           oteljava  avgt   80    672.001 ±    9.229    B/op
addParams …
```
> SpanBuilder: chain modifyState functions

- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/SdkTracerProvider.scala
- sdk/trace/src/main/scala/org/typelevel/otel4s/sdk/trace/processor/BatchSpanProcessor.scala
- sdk/trace/src/test/scala/org/typelevel/otel4s/sdk/trace/SdkTracerProviderSuite.scala
For the sake of consistency with oteljava.
> sdk-trace: use `TracerProvider.noop` when span processors aren't configured

- sdk/metrics/src/main/scala/org/typelevel/otel4s/sdk/metrics/exporter/PeriodicMetricReader.scala
- sdk/metrics/src/test/scala/org/typelevel/otel4s/sdk/metrics/exporter/PeriodicMetricReaderSuite.scala
Without this fix, the metrics aren't exported in short-lived applications. For example:
```scala
def run: IO[Unit] =
OpenTelemetrySdk
.autoConfigured[IO](_.addExportersConfigurer(OtlpExportersAutoConfigure[IO]))
.use { otel4s =>
otel4s.sdk.meterProvider.get("meter").flatMap { m =>
m.counter[Long]("my_service_counter").create.flatMap(_.inc())
}
}
```
> sdk-metrics: flush PeriodicMetricReader upon finalization

- core/common/src/main/scala/org/typelevel/otel4s/AnyValue.scala
- core/common/src/test/scala/org/typelevel/otel4s/AnyValueSuite.scala
- core/common/src/test/scala/org/typelevel/otel4s/scalacheck/Arbitraries.scala
- core/common/src/test/scala/org/typelevel/otel4s/scalacheck/Cogens.scala
- core/common/src/test/scala/org/typelevel/otel4s/scalacheck/Gens.scala
The specification: https://opentelemetry.io/docs/specs/otel/logs/data-model/#type-any.
Proto specification: https://github.com/open-telemetry/opentelemetry-proto/blob/v1.5.0/opentelemetry/proto/common/v1/common.proto#L28-L40
That's the first step towards https://github.com/typelevel/otel4s/issues/994. 
The `AnyValue` represents the body of the log. For example, `AnyValue.string("my log message")` represents a string log entry.
> core-common: add `AnyValue`

- core/logs/src/main/scala/org/typelevel/otel4s/logs/LogRecordBuilder.scala
The spec: https://opentelemetry.io/docs/specs/otel/logs/api/#emit-a-logrecord
> core-logs: add LogRecordBuilder

- docs/oteljava/metrics-jvm-runtime.md
Simplify docs about JVM metrics by using `Resource.fromAutoCloseable`
> Use Resource.fromAutoCloseable in docs

- build.sbt
- oteljava/testkit/src/main/scala/org/typelevel/otel4s/oteljava/testkit/OtelJavaTestkit.scala
- oteljava/trace-testkit/src/main/scala/org/typelevel/otel4s/oteljava/testkit/trace/TracesTestkit.scala
> oteljava: add `TracesTestkit#resetSpans`

- build.sbt
- core/common/src/main/scala/org/typelevel/otel4s/baggage/BaggageManager.scala
- core/common/src/main/scala/org/typelevel/otel4s/meta/InstrumentMeta.scala
- core/logs/src/main/scala/org/typelevel/otel4s/logs/LogRecordBuilder.scala
- core/logs/src/main/scala/org/typelevel/otel4s/logs/Logger.scala
- core/logs/src/main/scala/org/typelevel/otel4s/logs/LoggerBuilder.scala
- core/logs/src/main/scala/org/typelevel/otel4s/logs/LoggerProvider.scala
- core/trace/src/main/scala/org/typelevel/otel4s/trace/Span.scala
- core/trace/src/main/scala/org/typelevel/otel4s/trace/SpanBuilder.scala
- core/trace/src/main/scala/org/typelevel/otel4s/trace/SpanOps.scala
- core/trace/src/main/scala/org/typelevel/otel4s/trace/Tracer.scala
- core/trace/src/main/scala/org/typelevel/otel4s/trace/TracerBuilder.scala
- core/trace/src/main/scala/org/typelevel/otel4s/trace/TracerProvider.scala
- core/trace/src/test/scala/org/typelevel/otel4s/trace/BaseTracerSuite.scala
Rename `mapK` methods that take a `KindTransformer` to `liftTo`.
This change is preparation for #1001
> Rename most `mapK` methods to `liftTo`

- sdk/logs/src/main/scala/org/typelevel/otel4s/sdk/logs/data/LogRecordData.scala
- sdk/logs/src/test/scala/org/typelevel/otel4s/sdk/logs/data/LogRecordDataSuite.scala
- sdk/logs/src/test/scala/org/typelevel/otel4s/sdk/logs/scalacheck/Arbitraries.scala
- sdk/logs/src/test/scala/org/typelevel/otel4s/sdk/logs/scalacheck/Cogens.scala
- sdk/logs/src/test/scala/org/typelevel/otel4s/sdk/logs/scalacheck/Gens.scala
The spec: https://opentelemetry.io/docs/specs/otel/logs/data-model/.
> sdk-logs: add `LogRecordData`

- build.sbt
- docs/oteljava/testkit.md
- oteljava/logs-testkit/src/main/scala/org/typelevel/otel4s/oteljava/testkit/logs/LogsTestkit.scala
- oteljava/metrics-testkit/src/main/scala/org/typelevel/otel4s/oteljava/testkit/metrics/MetricsTestkit.scala
- oteljava/testkit/src/main/scala/org/typelevel/otel4s/oteljava/testkit/OtelJavaTestkit.scala
- oteljava/trace-testkit/src/main/scala/org/typelevel/otel4s/oteljava/testkit/trace/TracesTestkit.scala
Tell me if the `fromInMemory` in the inner Testkits is too much and I should just do a big one factory in the `OtelJavaTestkit`
Should I add an entry to the doc with an example of this?
> add fromInMemory on Testkits

- sdk-exporter/prometheus/src/main/scala/org/typelevel/otel4s/sdk/exporter/prometheus/PrometheusConverter.scala
- sdk-exporter/prometheus/src/main/scala/org/typelevel/otel4s/sdk/exporter/prometheus/PrometheusWriter.scala
- sdk-exporter/prometheus/src/test/scala/org/typelevel/otel4s/sdk/exporter/prometheus/PrometheusConverterSuite.scala
before this commit, if an unit is an annotation (for example {thread}) convertUnitName("{thread}") returns Right("") therefore we add an extra underscore at the end of prometheus name.
This commit is fixing this issue and also change the semantic of convertUnitName to ignore empty or an annotation unit instead of throw exception
Fix #1088
> Metrics SDK: Ignore empty and annotations unit
